- alias: 'dafang motion detected'
  trigger:
    payload: 'ON'
    platform: mqtt
    topic: home/dafang/motion
  action:
    service: notify.mypushbullet
    data:
      title: "Motion"
      message: "detected."
