- alias: "Lampka Jan on"
  trigger:
    platform: time
    at: '17:32:00'
  action:
    - service: mqtt.publish
      data:
        topic: "zigbee2mqtt/sonoff1/cmnd/POWER"
        payload: "ON"
- alias: "Lampka Jan off"
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: mqtt.publish
      data:
        topic: "zigbee2mqtt/sonoff1/cmnd/POWER"
        payload: "OFF"
