- alias: Listwa RTV off
  trigger:
    platform: time
    at: '02:00:00'
  action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/sonoff2/cmnd/POWER
        payload: OFF

- alias: Listwa RTV on
  trigger:
    platform: time
    at: '14:32:00'
  action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/sonoff2/cmnd/POWER
        payload: ON

- alias: Listwa RTV (weekend) on
  trigger:
    platform: time
    at: '07:32:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/sonoff2/cmnd/POWER
        payload: ON

- alias: Ambient tv on
  trigger:
    platform: time
    at: '17:32:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.yeelight_strip_7811dcda6e9e

- alias: Ambient tv off
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.yeelight_strip_7811dcda6e9e

- alias: Zmietek start
  trigger:
    platform: time
    at: '11:00:00'
  condition:
    - condition: time
      weekday:
      - mon
      - wed
      - fri
  action:
    - service: vacuum.start
      data:
        entity_id: vacuum.zmietekv2
