- alias: 'Włącz światło w korytarzu gdy ruch'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d000237ad9d_occupancy
      to: 'on'
    - platform: state
      entity_id: binary_sensor.0x00158d00020b7b77
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: group.korytarz_lampy
#    - service: tts.google_say
#      entity_id: media_player.tv
#      data:
#        message: 'Movement in korytarz'

- alias: 'Włącz timer w korytarzu gdy ruch'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d000237ad9d_occupancy
      to: 'on'
    - platform: state
      entity_id: binary_sensor.0x00158d00020b7b77
      to: 'on'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.korytarz
    - service: timer.start
      data:
        entity_id: timer.korytarz
#    - service: tts.google_say
#      entity_id: media_player.tv
#      data:
#        message: 'Movement in korytarz'


- alias: 'Wyłącz światło w korytarzu po upływie czasu'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.korytarz
  action:
    - service: light.turn_off
      data:
        entity_id: group.korytarz_lampy
#    - service: tts.google_say
#      entity_id: media_player.tv
#      data:
#        message: 'Nobody here, going sleep'

- alias: 'Otwarcie drzwi wejściowych'
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d00020b7b77
    to: 'on'
  condition:
    - condition: time
      after: '05:00:00'
      before: '23:59:59'
    - condition: state
      entity_id: group.mobiledevices
      state: not_home
  action:
    - service: notify.mypushbullet
      data_template:
        title: 'Korytarz drzwi'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Drzwi wejściowe zostały otwarte.

- alias: 'Chillout mode on'
  trigger:
    - platform: state
      entity_id: input_boolean.jasiu_chillout
      to: 'on'
    - platform: state
      entity_id: input_boolean.sypialnia_chillout
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.yeelight_ceiling_7811dcab824a
      data_template:
        brightness: 10
    - service: light.yeelight_set_mode
      data:
        entity_id: light.yeelight_ceiling_7811dcab824a
        mode: moonlight
    - service: light.turn_on
      entity_id: light.yeelight_ceiling4_7c49ebb70c4a
      data_template:
        brightness: 10
    - service: light.yeelight_set_mode
      data:
        entity_id: light.yeelight_ceiling4_7c49ebb70c4a
        mode: moonlight
    - service: light.turn_off
      data:
        entity_id: group.korytarz_lampy

- alias: 'Chillout mode off'
  trigger:
    - platform: state
      entity_id: input_boolean.jasiu_chillout
      to: 'off'
    - platform: state
      entity_id: input_boolean.sypialnia_chillout
      to: 'off'
  action:
    - service: light.turn_on
      entity_id: light.yeelight_ceiling_7811dcab824a
      data_template:
        brightness: 254
    - service: light.yeelight_set_mode
      data:
        entity_id: light.yeelight_ceiling_7811dcab824a
        mode: normal
    - service: light.turn_on
      entity_id: light.yeelight_ceiling4_7c49ebb70c4a
      data_template:
        brightness: 254
    - service: light.yeelight_set_mode
      data:
        entity_id: light.yeelight_ceiling4_7c49ebb70c4a
        mode: normal
    - service: light.turn_off
      data:
        entity_id: group.korytarz_lampy