- alias: 'Włącz światło w korytarzu gdy ruch'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d000237ad9d_occupancy
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: group.korytarz_lampy
    - service: timer.cancel
      data:
        entity_id: timer.korytarz
    - service: timer.start
      data:
        entity_id: timer.korytarz
    - service: tts.google_say
      data:
        message: 'Movement in korytarz'


- alias: 'Wyłącz światło w korytarzu po upływie czasu'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.korytarz
  action:
    - service: light.turn_off
      data:
        entity_id: group.korytarz_lampy
    - service: tts.google_say
      data:
        message: 'Nobody here, going sleep'

- alias: 'Otwarcie drzwi wejściowych'
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d00020b7b77
    to: 'on'
  condition:
    - condition: time
      after: '05:00:00'
      before: '23:59:59'
  action:
    - service: notify.mypushbullet
      data_template:
        title: 'Korytarz'
        message: |
          {{now().strftime("%a %b %d %H:%M:%S %p")}}
          Drzwi wejściowe zostały otwarte.
    - service: light.turn_on
      data:
        entity_id: group.korytarz_lampy
    - service: timer.cancel
      data:
        entity_id: timer.korytarz
    - service: timer.start
      data:
        entity_id: timer.korytarz

- alias: 'Wygaszanie światła korytarz'
  trigger:
    platform: time
    minutes: '/1'
    seconds: 00
  condition:
  - condition: state
    entity_id: light.yeelight_ceiling_7811dcab824a
    state: 'on'
  - condition: time
    after: '21:00:00'
    before: '23:59:00'
  action:
  - service: light.turn_on
    entity_id: light.yeelight_ceiling_7811dcab824a
    data_template:
      brightness: '{{states.light.yeelight_ceiling_7811dcab824a.attributes.brightness|int - 10}}'

- alias: 'Chillout mode on'
  trigger:
    - platform: state
      entity_id: input_boolean.jasiu_chillout
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.moonlight
    - service: light.turn_on
      entity_id: light.yeelight_ceiling_7811dcab824a
      data_template:
        brightness: 10
    - service: light.turn_off
      entity_id: light.yeelight_ceiling_7811dcab824a

- alias: 'Chillout mode off'
  trigger:
    - platform: state
      entity_id: input_boolean.jasiu_chillout
      to: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.moonlight
    - service: light.turn_on
      entity_id: light.yeelight_ceiling_7811dcab824a
      data_template:
        brightness: 254
