- alias: 'Włącz światło w korytarzu gdy ruch'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.korytarz_motion_occupancy
      to: 'on'
    - platform: state
      entity_id: binary_sensor.drzwi_wejsciowe_contact
      to: 'on'
  condition:
    - condition: state
      entity_id: light.lampa_korytarz_drzwi
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: group.korytarz_lampy
#    - service: tts.google_say
#      entity_id: media_player.tv
#      data:
#        message: 'Movement in korytarz'

- alias: 'Włącz timer w korytarzu gdy ruch'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.korytarz_motion_occupancy
      to: 'on'
    - platform: state
      entity_id: binary_sensor.drzwi_wejsciowe_contact
      to: 'on'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.korytarz
    - service: timer.start
      data:
        entity_id: timer.korytarz

- alias: 'Wyłącz światło w korytarzu po upływie czasu'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.korytarz
  condition:
    - condition: state
      entity_id: light.lampa_korytarz_drzwi
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: group.korytarz_lampy
#    - service: tts.google_say
#      entity_id: media_player.tv
#      data:
#        message: 'Nobody here, going sleep'

- alias: 'Otwarcie drzwi wejściowych'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.drzwi_wejsciowe_contact
    to: 'on'
  condition:
    - condition: time
      after: '05:00:00'
      before: '23:59:59'
    - condition: state
      entity_id: group.mobiledevices
      state: not_home
  action:
    - service: notify.mypushbullet
      data_template:
        title: 'Korytarz drzwi'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Drzwi wejściowe zostały otwarte.

- alias: 'Chillout mode on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.jasiu_chillout
      to: 'on'
    - platform: state
      entity_id: input_boolean.sypialnia_chillout
      to: 'on'
  condition:
    - condition: state
      entity_id: light.lampa_korytarz_drzwi
      state: 'on'
  action:
    - service: script.moonlight_korytarz_on

- alias: 'Chillout mode off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.jasiu_chillout
      to: 'off'
    - platform: state
      entity_id: input_boolean.sypialnia_chillout
      to: 'off'
  condition:
    - condition: state
      entity_id: light.lampa_korytarz_drzwi
      state: 'on'
  action:
    - service: script.moonlight_korytarz_off

- alias: 'Chillout mode on when first time lights turn on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.lampa_korytarz_drzwi
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ state_attr('light.lampa_korytarz_drzwi', 'brightness') > 100 }}"
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.sypialnia_chillout
          state: 'on'
        - condition: state
          entity_id: input_boolean.jasiu_chillout
          state: 'on'
  action:
    - service: script.moonlight_korytarz_on

- alias: 'Chillout mode off when first time lights turn on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.lampa_korytarz_drzwi
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.sypialnia_chillout
      state: 'off'
    - condition: state
      entity_id: input_boolean.jasiu_chillout
      state: 'off'
    - condition: template
      value_template: "{{ state_attr('light.lampa_korytarz_drzwi', 'brightness') < 100 }}"
  action:
    - service: script.moonlight_korytarz_off

- alias: 'Moonlight switch on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.moonlight_korytarz
      to: 'on'
  condition:
    - condition: state
      entity_id: light.lampa_korytarz_drzwi
      state: 'on'
  action:
    - service: script.moonlight_korytarz_on

- alias: 'Moonlight switch off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.moonlight_korytarz
      to: 'off'
  condition:
    - condition: state
      entity_id: light.lampa_korytarz_drzwi
      state: 'on'
  action:
    - service: script.moonlight_korytarz_off
