- alias: 'Włącz światło w korytarzu gdy ruch i otwarte drzwi'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d000237ad9d_occupancy, binary_sensor.0x00158d00020b7b77_2
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: group.korytarz_lampy
    - service: timer.start
      data:
        entity_id: timer.korytarz

- alias: 'Wyłącz światło w korytarzu po upływie czasu'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.korytarz
  action:
    - service: light.turn_on
      data:
        entity_id: group.korytarz_lampy
