- alias: 'Włącz światło w pokoju Janka gdy ruch'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00024e42b5
      to: 'on'
  condition:
    - condition: time
      after: '15:00:00'
      before: '23:59:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.yeelight_ceiling_7811dcab68e0
    - service: timer.start
      data:
        entity_id: timer.lazienka

- alias: 'Wyłącz światło w pokoju Janka po upływie czasu'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.lazienka
  action:
    - service: light.turn_off
      data:
        entity_id: light.yeelight_ceiling_7811dcab68e0
