- alias: 'Włącz światło w łazience gdy otwarte drzwi lub ruch'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.drzwi_lazienka_contact,binary_sensor.lazienka_motion_occupancy
      to: 'on'
  condition:
    - condition: state
      entity_id: light.lampa_lazienka
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.lampa_lazienka

- alias: 'Włącz timer w łazience gdy otwarte drzwi lub ruch'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.drzwi_lazienka_contact,binary_sensor.lazienka_motion_occupancy
      to: 'on'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.lazienka
    - service: timer.start
      data:
        entity_id: timer.lazienka

- alias: 'Wyłącz światło w łazience po upływie czasu'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.lazienka
  action:
    - service: light.turn_off
      data:
        entity_id: light.lampa_lazienka

- alias: 'Wyzeruj timer w łazience gdy światło zgaszone'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.lampa_lazienka
      to: 'off'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.lazienka

- alias: 'Zalanie łazienki'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.lazienka_leak_water_leak
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.listwa_salon_slot_4
    - service: notify.mypushbullet
      data_template:
        title: "!! Zalanie łazienki !!"
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Zalanie łazienki!!! Podgląd z kamery.

- alias: 'Włącz światło w toalecie gdy otwarte drzwi'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.drzwi_toaleta_contact
      to: 'on'
  condition:
    - condition: state
      entity_id: light.swiatlo_toaleta
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.swiatlo_toaleta

- alias: 'Wyłącz światło w toalecie przy wyjściu'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.drzwi_toaleta_contact
      to: 'on'
  condition:
    - condition: state
      entity_id: light.swiatlo_toaleta
      state: 'on'
  action:
    - delay: 00:00:01
    - service: light.turn_off
      data:
        entity_id: light.swiatlo_toaleta

- alias: 'Włącz timer w toalecie gdy otwarte drzwi'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.drzwi_toaleta_contact
      to: 'on'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.toaleta
    - service: timer.start
      data:
        entity_id: timer.toaleta

- alias: 'Wyłącz światło w toalecie po upływie czasu'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.toaleta
  action:
    - service: light.turn_off
      data:
        entity_id: light.swiatlo_toaleta

- alias: 'Wyzeruj timer w toalecie gdy światło zgaszone'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.swiatlo_toaleta
      to: 'off'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.toaleta
