- alias: 'Jan RTV off'
  initial_state: 'on'
  trigger:
    platform: time
    at: '00:05:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.listwa_jan_switch

- alias: 'Bedside Jan on'
  initial_state: 'on'
  trigger:
    platform: time
    at: '18:05:00'
  condition:
    - condition: state
      entity_id: light.bedside
      state: 'off'
    - condition: state
      entity_id: binary_sensor.bedside_online
      state: 'on'
    - condition: state
      entity_id: binary_sensor.home_occupied
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedside

- alias: 'Bedside Jan off'
  initial_state: 'on'
  trigger:
    platform: time
    at: '10:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.bedside

- alias: 'Włącz światło w pokoju Janka gdy ruch'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.janek_motion_occupancy
      to: 'on'
  condition:
    - condition: sun
      after: sunset
      after_offset: '-01:00:00'
    - condition: state
      entity_id: input_boolean.jasiu_chillout
      state: 'off'
    - condition: state
      entity_id: light.swiatlo_pokoj_janka
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.swiatlo_pokoj_janka

- alias: 'Włącz timer w pokoju Janka gdy ruch'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.janek_motion_occupancy
      to: 'on'
  condition:
    - condition: sun
      after: sunset
      after_offset: '-01:00:00'
    - condition: state
      entity_id: input_boolean.jasiu_chillout
      state: 'off'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.pokoj_janka
    - service: timer.start
      data:
        entity_id: timer.pokoj_janka

- alias: 'Wyłącz światło w pokoju Janka po upływie czasu'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.pokoj_janka
  action:
    - service: light.turn_off
      data:
        entity_id: light.swiatlo_pokoj_janka

- alias: 'Wyzeruj timer w pokoju Janka gdy światło zgaszone'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.swiatlo_pokoj_janka
      to: 'off'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.pokoj_janka

- alias: 'Przykręć ogrzewanie przy otwartym oknie w pokoju Janka'
#  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.okno_janek_contact
    to: 'on'
    for:
      seconds: 15
  condition:
    - condition: state
      entity_id: input_boolean.ogrzewanie
      state: 'on'
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.pokoj_janka
#    - service: notify.mypushbullet
#      data_template:
#        title: 'Ogrzewanie przykręcone w pokóju Janka'
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Ogrzewanie przykręcone w pokóju Janka

- alias: 'Przykręć ogrzewanie po powrocie przy nadal otwartym oknie w pokoju Janka'
#  initial_state: 'on'
  trigger:
    platform: state
    entity_id: climate.pokoj_janka
    to: 'heat'
  condition:
    - condition: state
      entity_id: binary_sensor.okno_janek_contact
      state: 'on'
    - condition: state
      entity_id: input_boolean.ogrzewanie
      state: 'on'
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.pokoj_janka

- alias: 'Przywróć ogrzewanie przy zamkniętym oknie w pokoju Janka'
#  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.okno_janek_contact
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.ogrzewanie
      state: 'on'
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.pokoj_janka
    - delay: 00:00:10
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.sypialnia
        hvac_mode: auto
#    - service: notify.mypushbullet
#      data_template:
#        title: 'Ogrzewanie przywrócone w pokóju Janka'
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Ogrzewanie przywrócone w pokóju Janka

- alias: 'Zgaś światło w pokoju Janka gdy chillout mode on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.jasiu_chillout
      to: 'on'
  condition:
    - condition: state
      entity_id: light.swiatlo_pokoj_janka
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.swiatlo_pokoj_janka
