- alias: 'Listwa sypialnia off'
  trigger:
    platform: time
    at: '03:00:00'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.listwa_sypialnia

- alias: 'Listwa sypialnia on'
  trigger:
    platform: time
    at: '20:00:00'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.listwa_sypialnia
  - service: notify.mypushbullet
    data:
      title: "Listwa sypialnia"
      message: "Enabled"

- alias: 'Listwa sypialnia (weekend) on'
  trigger:
    platform: time
    at: '08:00:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.listwa_sypialnia

- alias: 'Włącz światło w sypialni gdy ruch'
  trigger:
  - platform: state
    entity_id: binary_sensor.0x00158d0001e5d112_occupancy, binary_sensor.0x00158d0001e5d112_occupancy_2
    to: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.yeelight_ceiling_7811dcab824a
  - service: timer.start
    data:
      entity_id: timer.sypialnia

- alias: 'Wyłącz światło w sypialni po upływie czasu'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.sypialnia
  action:
  - service: light.turn_off
    data:
      entity_id: light.yeelight_ceiling_7811dcab824a
