- alias: "Lampka Jan on"
  trigger:
    platform: time
    at: '16:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.yeelight_bedside_7c49eb284fda
- alias: "Lampka Jan off"
  trigger:
    platform: time
    at: '07:30:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.yeelight_bedside_7c49eb284fda
