- alias: 'Listwa sypialnia notification'
  trigger:
    platform: time
    at: '03:00:00'
  condition:
    - condition: state
      entity_id: switch.listwa_sypialnia
      state: 'on'
  action:
    - service: notify.mypushbullet
      data_template:
        title: "Listwa sypialnia off"
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Listwa za 5 minut się wyłączy

- alias: 'Listwa sypialnia off'
  trigger:
    platform: time
    at: '03:05:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.listwa_sypialnia

- alias: 'Listwa sypialnia on'
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    - condition: state
      entity_id: switch.listwa_sypialnia
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.listwa_sypialnia
    - service: notify.mypushbullet
      data_template:
        title: "Sypialnia listwa on"
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Listwa on

- alias: 'Listwa sypialnia (weekend) on'
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    - condition: time
      weekday:
      - sat
      - sun
    - condition: state
      entity_id: switch.listwa_sypialnia
      state: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.listwa_sypialnia
    - service: notify.mypushbullet
      data_template:
        title: "Listwa sypialnia on"
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Listwa on

- alias: 'Włącz światło w sypialni gdy ruch'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0001e55705_occupancy
      to: 'on'
  condition:
    - condition: time
      after: '15:00:00'
      before: '23:59:00'
    - condition: state
      entity_id: input_boolean.sypialnia_chillout
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.yeelight_ceiling3_04cf8c78d9f7
    - service: timer.cancel
      data:
        entity_id: timer.sypialnia
    - service: timer.start
      data:
        entity_id: timer.sypialnia

- alias: 'Wyłącz światło w sypialni po upływie czasu'
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.sypialnia
  action:
    - service: light.turn_off
      data:
        entity_id: light.yeelight_ceiling3_04cf8c78d9f7

- alias: 'Wyzeruj timer w sypialni gdy światło zgaszone'
  trigger:
    - platform: state
      entity_id: light.yeelight_ceiling3_04cf8c78d9f7
      to: 'off'
  action:
    - service: timer.cancel
      data:
        entity_id: timer.sypialnia
