#- alias: 'Drzwi balkonowe otwarte'
#initial_state: 'on'
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.drzwi_balkonowe_contact
#      to: 'on'
#  action:
#    - service: notify.mypushbullet
#      data_template:
#        title: "Salon drzwi balkonowe"
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Odnotowano wyjście na fajkę

- alias: 'Zalanie kuchni'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.kuchnia_leak_water_leak
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.listwa_salon_slot_4
    - service: notify.mypushbullet
      data_template:
        title: "!! Zalanie kuchni !!"
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Zalanie kuchni!!! Podgląd z kamery.

- alias: 'Pozar w kuchni'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.kuchnia_smoke_detector
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.listwa_salon_slot_4
    - service: notify.mypushbullet
      data_template:
        title: "!! Pożar w kuchni !!"
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Pożar kuchni!!! Podgląd z kamery.

#- alias: 'Listwa RTV notification'
#  initial_state: 'on'
#  trigger:
#    platform: time
#    at: '02:00:00'
#  condition:
#    - condition: state
#      entity_id: switch.listwa_salon_slot_usb
#      state: 'on'
#  action:
#    - service: notify.mypushbullet
#      data_template:
#        title: "Salon listwa RTV off"
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Listwa za 5 minut się wyłączy
#
#- alias: 'Listwa RTV off'
#  initial_state: 'on'
#  trigger:
#    platform: time
#    at: '02:05:00'
#  action:
#    - service: switch.turn_off
#      data:
#        entity_id: switch.listwa_salon_slot_usb

#- alias: 'Listwa RTV off (for sure)'
#  initial_state: 'on'
#  trigger:
#    platform: time
#    at: '07:30:00'
#  action:
#    - service: switch.turn_off
#      data:
#        entity_id: switch.listwa_salon_slot_usb

#- alias: 'Listwa RTV on'
#  trigger:
#    platform: time
#    at: '16:30:00'
#  condition:
#    - condition: state
#      entity_id: switch.listwa_salon_slot_1
#      state: 'off'
#  action:
#    - service: switch.turn_on
#      data:
#        entity_id: switch.listwa_salon_slot_1
#    - service: notify.mypushbullet
#      data_template:
#        title: "Listwa RTV salon on"
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Listwa on
#
#- alias: 'Listwa RTV (weekend) on'
#  initial_state: 'on'
#  trigger:
#    platform: time
#    at: '07:32:00'
#  condition:
#    - condition: time
#      weekday:
#        - sat
#        - sun
#    - condition: state
#      entity_id: switch.listwa_salon_slot_usb
#      state: 'off'
#  action:
#    - service: switch.turn_on
#      data:
#        entity_id: switch.listwa_salon_slot_usb
#    - service: notify.mypushbullet
#      data_template:
#        title: "Listwa RTV salon on"
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Listwa on

- alias: 'Ambient on'
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  condition:
    - condition: state
      entity_id: group.mobiledevices
      state: home
  action:
    - service: script.ambient_on

- alias: 'Ambient off'
  initial_state: 'on'
  trigger:
    platform: time
    at: '02:04:00'
  action:
    - service: script.ambient_off

- alias: 'Zmietek start'
  initial_state: 'on'
  trigger:
    platform: time
    at: '11:00:00'
  condition:
    - condition: time
      weekday:
      - mon
      - wed
      - fri
  action:
    - service: script.zmietek_start

- alias: 'Zmietek docked'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: vacuum.zmietekv2
      from: 'returning'
      to: 'docked'
  action:
    - service: notify.mypushbullet
      data_template:
        title: 'Zmietek zakończył sprzątanie'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Zmietek zakończył sprzątanie po {{ state_attr('vacuum.zmietekv2', 'cleaning_time') }} minutach, powierchnię {{ state_attr('vacuum.zmietekv2', 'cleaned_area') }} m2 z poziomem baterii {{ state_attr('vacuum.zmietekv2', 'battery_level') }} %.

- alias: 'Zmietek error'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: vacuum.zmietekv2
      to: 'error'
  action:
    - service: notify.mypushbullet
      data_template:
        title: 'Zmietek napotkał problem'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Zmietek po {{ state_attr('vacuum.zmietekv2', 'cleaning_time') }} minutach sprzątania {{ state_attr('vacuum.zmietekv2', 'cleaned_area') }} m2 zatrzymał się z powodu błędu.
          {{ state_attr('vacuum.zmietekv2', 'error') }}

- alias: 'Włącz ładowanie zmietka po sprzątaniu'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.vacuum_status
      to: 'Returning home'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.zmietek

- alias: 'Wyłącz ładowanie zmietka przy 100% baterii'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.vacuum_battery
      to: '100'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.zmietek

- alias: 'Włącz listwę i ampli przy włączeniu tv'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.sony_bravia_tv
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.listwa_salon_slot_1
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.listwa_salon_slot_1
    - delay: 00:00:05
    - service: input_select.select_option
      data:
        entity_id: input_select.broadlink_denon_input
        option: 'TV'

#- alias: 'Włącz ampli przy włączaniu listwy i wlaczonym tv'
#  trigger:
#    - platform: state
#      entity_id: switch.listwa_salon_slot_1
#      to: 'on'
#  condition:
#    - condition: state
#      entity_id: media_player.sony_bravia_tv
#      state: 'on'
#  action:
#    - delay: 00:00:10
#    - service: input_boolean.turn_on
#      data:
#        entity_id: input_boolean.broadlink_denon_receiver
#
#- alias: 'Włącz ampli przy włączonej listwie i wlaczaniu tv'
#  trigger:
#    - platform: state
#      entity_id: media_player.sony_bravia_tv
#      to: 'on'
#  condition:
#    - condition: state
#      entity_id: input_boolean.broadlink_denon_receiver
#      state: 'off'
#  action:
#    - service: input_boolean.turn_on
#      data:
#        entity_id: input_boolean.broadlink_denon_receiver
#
- alias: 'Wyłącz ampli przy wyłączonym tv'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.sony_bravia_tv
      to: 'off'
      for:
        seconds: 45
  condition:
    - condition: state
      entity_id: switch.listwa_salon_slot_1
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.listwa_salon_slot_1

- alias: 'Przykręć ogrzewanie przy otwartych drzwiach w salonie'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.drzwi_balkonowe_contact
    to: 'on'
    for:
      seconds: 15
  condition:
    - condition: state
      entity_id: input_boolean.ogrzewanie
      state: 'on'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.salon
        preset_mode: 'away'
    - service: notify.mypushbullet
      data_template:
        title: 'Ogrzewanie przykręcone w salonie'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Ogrzewanie przykręcone w salonie

- alias: 'Przykręć ogrzewanie po powrocie przy nadal otwartych drzwiach w salonie'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: climate.salon
    to: 'heat'
  condition:
    - condition: state
      entity_id: binary_sensor.drzwi_balkonowe_contact
      state: 'on'
    - condition: state
      entity_id: input_boolean.ogrzewanie
      state: 'on'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.salon
        preset_mode: 'away'

- alias: 'Przywróć ogrzewanie przy zamkniętych drzwiach w salonie'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.drzwi_balkonowe_contact
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.ogrzewanie
      state: 'on'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.salon
        preset_mode: 'home'
    - service: notify.mypushbullet
      data_template:
        title: 'Ogrzewanie przywrócone w salonie'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Ogrzewanie przywrócone w salonie

- alias: 'Wyłącz ambient przyciskiem regału'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.salon_regal
      to: 'off'
  action:
    - service: script.ambient_off

- alias: 'Włącz ambient przyciskiem regału'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.salon_regal
      to: 'on'
  action:
    - service: script.ambient_on
