- alias: 'Choinka off'
  trigger:
    platform: time
    at: '02:00:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.choinka

- alias: 'Choinka on'
  trigger:
    platform: time
    at: '15:30:00'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.choinka

- alias: 'Listwa RTV off'
  trigger:
    platform: time
    at: '02:00:00'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.listwa_rtv

- alias: 'Listwa RTV off (for sure)'
  trigger:
    platform: time
    at: '07:30:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.listwa_rtv

- alias: 'Listwa RTV on'
  trigger:
    platform: time
    at: '15:30:00'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.listwa_rtv

- alias: 'Listwa RTV (weekend) on'
  trigger:
    platform: time
    at: '07:32:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.listwa_rtv

- alias: 'Ambient tv on'
  trigger:
    platform: time
    at: '15:30:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.yeelight_strip_7811dcda6e9e
    - service: light.turn_on
      data:
        entity_id: light.yeelight_strip_7811dce2d84e
    - service: notify.mypushbullet
      data:
        title: "Salon"
        message: "Ambient on"

- alias: 'Ambient tv off'
  trigger:
    platform: time
    at: '07:05:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.yeelight_strip_7811dcda6e9e
    - service: light.turn_off
      data:
        entity_id: light.yeelight_strip_7811dce2d84e

- alias: 'Zmietek start'
  trigger:
    platform: time
    at: '11:00:00'
  condition:
    - condition: time
      weekday:
      - mon
      - wed
      - fri
  action:
    - service: vacuum.start
      data:
        entity_id: vacuum.zmietekv2
    - service: notify.mypushbullet
      data:
        title: "Salon"
        message: "Zmietek start"