- alias: 'Drzwi balkonowe otwarte'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d000205b35f
      to: 'on'
  action:
    - service: notify.mypushbullet
      data_template:
        title: "Salon drzwi balkonowe"
        message: "Odnotowano wyjście na fajkę"

- alias: 'Choinka off'
  trigger:
    platform: time
    at: '02:00:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.choinka

- alias: 'Choinka on'
  trigger:
    platform: time
    at: '15:30:00'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.choinka
    - service: notify.mypushbullet
      data_template:
        title: "Salon choinka on"
        message: "Choinka on"

- alias: 'Choinka (weekend) on'
  trigger:
    platform: time
    at: '07:32:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.choinka

- alias: 'Listwa RTV notification'
  trigger:
    platform: time
    at: '02:00:00'
  action:
    - service: notify.mypushbullet
      data_template:
        title: "Salon Listwa RTV off"
        message: "Listwa RTV za 5 minut się wyłączy"

- alias: 'Listwa RTV off'
  trigger:
    platform: time
    at: '02:05:00'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.listwa_rtv

- alias: 'Listwa RTV off (for sure)'
  trigger:
    platform: time
    at: '07:30:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.listwa_rtv

- alias: 'Listwa RTV on'
  trigger:
    platform: time
    at: '15:30:00'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.listwa_rtv

- alias: 'Listwa RTV (weekend) on'
  trigger:
    platform: time
    at: '07:32:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.listwa_rtv

- alias: 'Ambient tv on'
  trigger:
    platform: time
    at: '15:30:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.yeelight_strip_7811dcda6e9e
    - service: light.turn_on
      data:
        entity_id: light.yeelight_strip_7811dce2d84e
    - service: notify.mypushbullet
      data_template:
        title: "Salon ambient on"
        message: "Ambient on"

- alias: 'Ambient tv off'
  trigger:
    platform: time
    at: '02:04:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.yeelight_strip_7811dcda6e9e
    - service: light.turn_off
      data:
        entity_id: light.yeelight_strip_7811dce2d84e

- alias: 'Zmietek start'
  trigger:
    platform: time
    at: '11:00:00'
  condition:
    - condition: time
      weekday:
      - mon
      - wed
      - fri
  action:
    - service: vacuum.start
      data:
        entity_id: vacuum.zmietekv2
    - service: notify.mypushbullet
      data_template:
        title: "Salon zmietek start"
        message: "Zmietek start"