  - id: power-ha
    alias: "Power state on HA start-up"
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "zigbee2mqtt/sonoff2/cmnd/POWER"
          payload: ""
      - service: mqtt.publish
        data:
          topic: "zigbee2mqtt/sonoff1/cmnd/POWER"
          payload: ""
      - service: mqtt.publish
        data:
          topic: "basic/sonoff-basic-3/cmnd/POWER"
          payload: ""
  - id: ambient-tv-on
    alias: "Ambinet tv on"
    trigger:
      platform: time
      at: '17:32:00'
    action:
      - service: light.turn_on
        data:
          entity_id: light.yeelight_strip_7811dcda6e9e
  - id: ambient-tv-off
    alias: "Ambinet tv off"
    trigger:
      platform: time
      at: '07:00:00'
    action:
      - service: light.turn_off
        data:
          entity_id: light.yeelight_strip_7811dcda6e9e
          payload: ""
  - id: lampka-jan-on
    alias: "Lampka Jan on"
    trigger:
      platform: time
      at: '17:32:00'
    action:
      - service: mqtt.publish
        data:
          topic: "zigbee2mqtt/sonoff1/cmnd/POWER"
          payload: "ON"
  - id: lampka-jan-off
    alias: "Lampka Jan off"
    trigger:
      platform: time
      at: '07:00:00'
    action:
      - service: mqtt.publish
        data:
          topic: "zigbee2mqtt/sonoff1/cmnd/POWER"
          payload: "OFF"
          payload: ""
  - id: listwa-rtv-on
    alias: "Listwa RTV on"
    trigger:
      platform: time
      at: '13:32:00'
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: mqtt.publish
        data:
          topic: "zigbee2mqtt/sonoff2/cmnd/POWER"
          payload: "ON"
  - id: listwa-rtv-off
    alias: "Listwa RTV off"
    trigger:
      platform: time
      at: '02:00:00'
    action:
      - service: mqtt.publish
        data:
          topic: "zigbee2mqtt/sonoff2/cmnd/POWER"
          payload: "OFF"
          payload: ""
  - id: listwa-rtv-weekend-on
    alias: "Listwa RTV (weekend) on"
    trigger:
      platform: time
      at: '07:32:00'
    condition:
      - condition: time
        weekday:
          - sat
          - sun
    action:
      - service: mqtt.publish
        data:
          topic: "zigbee2mqtt/sonoff2/cmnd/POWER"
          payload: "ON"
  - id: zmietek-start
    alias: "Zmietek start"
    trigger:
      platform: time
      at: '11:00:00'
    condition:
      - condition: time
        weekday:
          - mon
          - wed
          - fri
    action:
      - service: vacuum.start
        data:
          entity_id: vacuum.zmietekv2

