homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 100
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  #  customize: !include customize.yaml
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
  customize: !include_dir_merge_named customizations

# Show links to resources in log and frontend
#introduction:
logger:
  default: info

# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:
zeroconf:

lovelace:
  mode: yaml

#customizer:
#  custom_ui: local

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

http:
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_key_path

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - belkin_wemo
    - bluesound
    - bose_soundtouch
    - denonavr
    - frontier_silicon
    - harmony
    - ikea_tradfri
    - logitech_mediaserver
    - netgear_router
    - openhome
    - panasonic_viera
    - philips_hue
    - plex_mediaserver
    - roku
    - sabnzbd
    - samsung_printer
    - sonos
    - songpal
    - tellstick
    - wink
    - yamaha
    - xiaomi_gw

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - weblink

recorder:
  purge_interval: 3
  purge_keep_days: 90
  db_url: sqlite:////home/homeassistant/.homeassistant/home-assistant_v2_recorder.db
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date


# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:
zone: !include_dir_merge_list zones

# Track the sun
sun:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# Text to speech
tts:
  - platform: google

camera: !include cameras/dafang.yaml
timer: !include timer/timer.yaml
group: !include_dir_named groups
automation: !include_dir_merge_list automation
script: !include_dir_named scripts
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
weblink: !include weblink.yaml
switch: !include_dir_merge_list switches
cover: !include cover/shellys.yaml
input_boolean: !include input_boolean.yaml
input_select: !include_dir_merge_named input_selects
weather: !include weather/darksky.yaml
light: !include_dir_merge_list lights

mqtt:
  discovery: true
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.133
    name: zmietekv2
    token: !secret vacuum

notify:
  - name: mypushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

climate:
  - platform: eq3btsmart
    devices:
      pokoj-janka:
        mac: '00:1A:22:0C:1A:F2'
      sypialnia:
        mac: '00:1A:22:0C:1A:EF'

asuswrt:
  host: 192.168.1.1
  username: !secret device_tracker_asus_username
  password: !secret device_tracker_asus_password

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret device_tracker_asus_username
    password: !secret device_tracker_asus_password
    interval_seconds: 60
    new_device_defaults:
      track_new_devices: false
      hide_if_away: true

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - vacuum
    - climate
    - cover
    - media_player
