homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.4046033
  longitude: 16.8606243
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 100
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
#  customize: !include customize.yaml
  customize: !include_dir_merge_named customizations

# Show links to resources in log and frontend
#introduction:
logger:
  default: info

# Enables the frontend
frontend:

# Enables configuration UI
config:
zeroconf:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - igd

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater

recorder:
  purge_keep_days: 5
  db_url: sqlite:////home/homeassistant/.homeassistant/home-assistant_v2_recorder.db
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date


# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# Text to speech
#tts:
#  - platform: google

# Cloud
#cloud:

camera: !include cameras/dafang.yaml
group: !include_dir_named groups
automation: !include_dir_merge_list automation
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
weblink: !include weblink.yaml
switch: !include_dir_merge_list switches

mqtt:
  discovery: true
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.133
    name: zmietekv2
    token: !secret vacuum

notify:
  - name: mypushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

climate:
  - platform: eq3btsmart
    devices:
      pokoj-janka:
        mac: '00:1A:22:0C:1A:F2'
      sypialnia:
        mac: '00:1A:22:0C:1A:EF'
