resources:
  - url: /local/custom_ui/tracker-card.js?track=true
    type: module
  - url: /local/custom_ui/tasmota-tracker-card.js?v=0.1.1
    type: js
  - url: /local/custom_ui/dark-sky-weather-card.js?track=true
    type: js
  - url: /local/custom_ui/mini-media-player-bundle.js?track=true
    type: module
  - url: /local/custom_ui/mini-graph-card-bundle.js?track=true
    type: module
  - url: /local/custom_ui/card-modder.js?track=true
    type: module
  - url: /local/custom_ui/card-tools.js?track=true
    type: js
  - url: /local/custom_ui/compact-custom-header/compact-custom-header.js?track=true
    type: module
  - url: /local/custom_ui/kiosk.js?track=true
    type: js

title: Zene Home
views:
  - !include lovelace/salon_view.yaml
  - !include lovelace/korytarz_view.yaml
  - !include lovelace/pokoj_janka_view.yaml
  - !include lovelace/sypialnia_view.yaml
  - !include lovelace/lazienka_view.yaml
  - !include lovelace/security_view.yaml
  - !include lovelace/automation_view.yaml
  - !include lovelace/system_status_view.yaml
  - !include lovelace/battery_view.yaml
