custom_header:
  compact_mode: true
  swipe_animate: fade
  swipe_prevent_default: true
  voice_hide: true
  hide_help: true
  hide_unused: true
  hide_config: true
  hide_raw: true
  chevrons: false
  exceptions:
    - conditions:
        query_string: kiosk
      config:
        kiosk_mode: true
resources:
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /local/custom_ui/tasmota-tracker-card.js?v=0.1.1
    type: js
  - url: /local/custom_ui/dark-sky-weather-card.js?v=7.1
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /local/custom_ui/card-modder.js?track=true
    type: module
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: module
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /local/custom_ui/kiosk.js?track=true
    type: js
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /local/custom_ui/flower-card/flower-card.js?v=0.2
    type: module
  - url: /community_plugin/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
    type: module
#  - url: /community_plugin/check-button-card/check-button-card.js
#    type: module
#  - url: /community_plugin/simple-thermostat/simple-thermostat.js
#    type: module
  - url: /community_plugin/spotify-card/spotify-card.js
    type: module
  - url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: module
cch:
  menu: overflow
  voice: hide
  hide_help: true
  header: true
  background: true
  notification: overflow
  options: show
  swipe: false
  kiosk_mode: false

title: Zene Home
views:
  - !include lovelace/salon_view.yaml
  - !include lovelace/korytarz_view.yaml
  - !include lovelace/pokoj_janka_view.yaml
  - !include lovelace/sypialnia_view.yaml
  - !include lovelace/weather_view.yaml
#  - !include lovelace/lazienka_view.yaml
  - !include lovelace/security_view.yaml
#  - !include lovelace/automation_view.yaml
  - !include lovelace/system_status_view.yaml
  - !include lovelace/battery_view.yaml
