resources:
  - url: /local/custom_ui/dark-sky-weather-card.js?v=4
    type: js
  - url: /local/custom_ui/mini-media-player-bundle.js?v=0.9.8
    type: module
  - url: /local/custom_ui/tracker-card.js?v=0.1.5
    type: js
  - url: /local/custom_ui/surveillance-card.js?v=0.0.1
    type: module
  - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.1.0
    type: module
  - url: /local/custom_ui/card-modder.js?v=fadc03
    type: module
  - url: /local/custom_ui/slider-entity-row.js?v=d6da75
    type: js
  - url: /local/custom_ui/card-tools.js?v=6ce5d0
    type: js
  - url: /local/custom_ui/compact-custom-header/compact-custom-header.js?v=0.2.7
    type: js
  - url: /local/custom_ui/waze-card.js?v=1.1.1
    type: js
  - url: /local/custom_ui/circle-sensor-card.js?v=1.2.0
    type: module
  - url: /local/custom_ui/monster-card.js?v=0.2.3
    type: js

title: Zene Home
views:
  - !include lovelace/default_view.yaml
  - !include lovelace/salon.yaml
  - !include lovelace/korytarz.yaml
  - !include lovelace/pokoj_janka.yaml
  - !include lovelace/sypialnia.yaml
  - !include lovelace/lazienka.yaml
  - !include lovelace/other_view.yaml
  - !include lovelace/weather_view.yaml
  - !include lovelace/automation_view.yaml
