title: Zene Home
views:
  - !include lovelace/default_view.yaml
  - !include lovelace/salon.yaml
  - !include lovelace/korytarz.yaml
  - !include lovelace/pokoj_janka.yaml
  - !include lovelace/sypialnia.yaml
  - !include lovelace/other_view.yaml
  - !include lovelace/weather_view.yaml
  - !include lovelace/automation_view.yaml
