resources:
  - url: /local/custom_ui/tracker-card.js?v=0
    type: js
  - url: /local/custom_ui/dark-sky-weather-card.js?v=4
    type: js
  - url: /local/custom_ui/mini-media-player-bundle.js?v=0.9.8
    type: module
  - url: /local/custom_ui/mini-graph-card-bundle.js?v=0.2.1
    type: module
  - url: /local/custom_ui/card-modder.js?v=0.3
    type: module
  - url: /local/custom_ui/slider-entity-row.js?v=d6da75
    type: js
  - url: /local/custom_ui/card-tools.js?v=0.3
    type: js
  - url: /local/custom_ui/compact-custom-header/compact-custom-header.js?v=0.2.9
    type: js
  - url: /local/custom_ui/kiosk.js?v=1.0.0
    type: js

title: Zene Home
views:
  - !include lovelace/salon_view.yaml
  - !include lovelace/korytarz.yaml
  - !include lovelace/pokoj_janka.yaml
  - !include lovelace/sypialnia.yaml
  - !include lovelace/lazienka.yaml
  - !include lovelace/weather_view.yaml
  - !include lovelace/security_view.yaml
  - !include lovelace/automation_view.yaml
  - !include lovelace/system_status_view.yaml
