- platform: broadlink
  friendly_name: broadlink
  timeout: 15
  host: 192.168.1.163
  mac: '78:0F:77:D9:23:FA'
  type: rm_mini
  switches:
    denon_power:
      friendly_name: "Denon power"
      command_on: "JgBQAAgbCF8IGggbBz0KGQsXCRoIXwg9Bz0GHAgABcgKGAg8CD0IGghfCTwLOgg8CD0IGweBCgAFowkaBz0IGgg9CzoJPAg9Bj4IgQkaCxcHAA0FAAAAAAAAAAA="
      command_off: "JgCAAAgaCF8JGQo7CF8IGwhfCD0IPAYcCAAFyAkZCDwHPggaCD0HGwt/CDwJPAhfBz0IAAWlCBsHPQgaBz4JXgccCD0IPAmABxwHGwcABcgIPAgbBxsHYAgbCjsIPAg9BxsIGwldCD0IAAWkCV4IPQkaCF8JGgY+CIEIPAkaBxsIAA0FAAAAAAAAAAA="
    denon_volume:
      friendly_name: "Denon volume"
      command_on: "JgBSAAgaCl0JGgleCRkIGwgaCYAIPQc9BxwJAAXGCBoHPgk8CBoJGgY+CTsHPggaCjsJGgmACQAFpAgaCV4JPAg8CzoJGgY+CD0JPAU/CBoJGgcADQUAAAAAAAA="
      command_off: "JgBMAAgaC1wIGwg8CV8IGgiBCjoIPQgaCwAFxAwXBz4KOwgaCV4IgAsYCzoJGQk8CD0KAAWiDBcKOgccCD0IGgpdC1wIPAt/ChgIGwYADQUAAAAAAAAAAAAAAAA="
