- platform: rest
  resource: http://127.0.0.1:8126/container/mosquitto
  name: Mosquitto
  body_on: '{"state": "unpause"}'
  body_off: '{"state": "pause"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/ha-dockermon
  name: ha-dockermon
  body_on: '{"state": "unpause"}'
  body_off: '{"state": "pause"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/nicolargo-glances
  name: nicolargo-glances
  body_on: '{"state": "unpause"}'
  body_off: '{"state": "pause"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/nextcloud
  name: nextcloud
  body_on: '{"state": "unpause"}'
  body_off: '{"state": "pause"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/zigbee2mqtt
  name: zigbee2mqtt
  body_on: '{"state": "unpause"}'
  body_off: '{"state": "pause"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/mariadb
  name: mariadb
  body_on: '{"state": "unpause"}'
  body_off: '{"state": "pause"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/letsencrypt
  name: letsencrypt
  body_on: '{"state": "unpause"}'
  body_off: '{"state": "pause"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/homeassistant
  name: homeassistant
  body_on: '{"state": "unpause"}'
  body_off: '{"state": "pause"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/plex
  name: plex
  body_on: '{"state": "unpause"}'
  body_off: '{"state": "pause"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://127.0.0.1:8126/container/youtube-dl
  name: youtube-dl
  body_on: '{"state": "unpause"}'
  body_off: '{"state": "pause"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
