- platform: template
  switches:
    xiaomi_humidifier_led:
      friendly_name: "LED"
      value_template: "{{ is_state_attr('fan.smartmi2', 'led', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_led_on
        data:
          entity_id: fan.smartmi2
      turn_off:
        service: xiaomi_miio.fan_set_led_off
        data:
          entity_id: fan.smartmi2
      icon_template: "mdi:lightbulb-outline"
    xiaomi_humidifier_child_lock:
      friendly_name: "Child lock"
      value_template: "{{ is_state_attr('fan.smartmi2', 'child_lock', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_child_lock_on
        data:
          entity_id: fan.smartmi2
      turn_off:
        service: xiaomi_miio.fan_set_child_lock_off
        data:
          entity_id: fan.smartmi2
      icon_template: "mdi:lock-outline"
    xiaomi_humidifier_buzzer:
      friendly_name: "Buzzer"
      value_template: "{{ is_state_attr('fan.smartmi2', 'buzzer', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_buzzer_on
        data:
          entity_id: fan.smartmi2
      turn_off:
        service: xiaomi_miio.fan_set_buzzer_off
        data:
          entity_id: fan.smartmi2
      icon_template: "mdi:volume-high"
