- platform: mqtt
  name: "Swiato Pokoj Janka"
  state_topic: "shellies/shellyswitch-55A0C8/relay/0"
  command_topic: "shellies/shellyswitch-55A0C8/relay/0"
  availability_topic: "shellies/shellyswitch-55A0C8/online"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
