- platform: mqtt
  name: "Kamera"
  state_topic: "basic/sonoff-basic-3/POWER"
  command_topic: "basic/sonoff-basic-3/cmnd/POWER"
  availability_topic: "basic/sonoff-basic-3/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Listwa RTV"
  state_topic: "zigbee2mqtt/sonoff2/POWER"
  command_topic: "zigbee2mqtt/sonoff2/cmnd/POWER"
  availability_topic: "zigbee2mqtt/sonoff2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Listwa Sypialnia"
  state_topic: "zigbee2mqtt/sonoff1/POWER"
  command_topic: "zigbee2mqtt/sonoff1/cmnd/POWER"
  availability_topic: "zigbee2mqtt/sonoff1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: "Choinka"
  state_topic: "zigbee2mqtt/sonoff4/POWER"
  command_topic: "zigbee2mqtt/sonoff4/cmnd/POWER"
  availability_topic: "zigbee2mqtt/sonoff4/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false