- platform: mqtt
  name: maintenance_check_humidifier
  state_topic: 'homeassistant/sensor/maintenance_humidifier/state'
  unit_of_measurement: timestamp
- platform: mqtt
  name: maintenance_check_kratki
  state_topic: 'homeassistant/sensor/maintenance_kratki/state'
  unit_of_measurement: timestamp
