- platform: mqtt
  name: Humidifier maintenance
  state_topic: 'homeassistant/sensor/maintenance_humidifier/state'
- platform: mqtt
  name: Kratki maintenance
  state_topic: 'homeassistant/sensor/maintenance_kratki/state'
