- platform: "mqtt"
  name: "drzwi_balkonowe_contact_battery"
  state_topic: "zigbee2mqtt/0x00158d000205b35f"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "drzwi_wejsciowe_contact_battery"
  state_topic: "zigbee2mqtt/0x00158d00020b7b77"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "okno_janek_contact_battery"
  state_topic: "zigbee2mqtt/0x00158d000208e0c7"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "okno_sypialnia_contact_battery"
  state_topic: "zigbee2mqtt/0x00158d0002bfd324"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "drzwi_lazienka_contact_battery"
  state_topic: "zigbee2mqtt/0x00158d00024e42b5"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "drzwi_toaleta_contact_battery"
  state_topic: "zigbee2mqtt/0x00158d0002b52fd0"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "okno_kuchnia_contact_battery"
  state_topic: "zigbee2mqtt/0x00158d00032169f8"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"
