- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - summary
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - pressure
    - humidity
#- platform: yr
#  name: Weather
#  forecast: 24
#  monitored_conditions:
#  - temperature
#  - symbol
#  - precipitation
#  - windSpeed
#  - pressure
#  - humidity