- platform: darksky
  api_key: !secret darksky_api
  language: pl
  static_icons: false
  tooltip_bg_color: 'rgb( 75,155,239)'
  tooltip_border_color: orange
  tooltip_border_width: 3
  tooltip_caret_size: 10
  tooltip_fg_color: '#fff'
  tooltip_left_offset: -12
  tooltip_width: 100
  tooltips: true
  old_daily_format: false
  time_format: 24
  show_beaufort: true
  forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  monitored_conditions:
    - icon
    - summary
    - nearest_storm_distance
    - nearest_storm_bearing
    - humidity
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - wind_speed
    - wind_bearing
    - precip_type
    - precip_probability
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - uv_index
    - daily_summary
    - pressure
    - visibility
  scan_interval:
    minutes: 5
