- platform: "mqtt"
  name: "kuchnia_leak_battery"
  state_topic: "zigbee2mqtt/0x00158d00021508b4"
  availability_topic: "zigbee2mqtt/0x00158d00021508b4/availability"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "lazienka_leak_battery"
  state_topic: "zigbee2mqtt/0x00158d0001bb388f"
  availability_topic: "zigbee2mqtt/0x00158d0001bb388f/availability"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"
