- platform: miflora
  name: Zamioculcas zamiifolia
  mac: 'C4:7C:8D:6A:01:92'
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
- platform: miflora
  name: Sansevieria trifasciata
  mac: 'C4:7C:8D:69:FE:F0'
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
