- platform: "mqtt"
  name: "lazienka_motion_illuminance"
  state_topic: "zigbee2mqtt/0x00158d0001e0a7d3"
  availability_topic: "zigbee2mqtt/0x00158d0001e0a7d3/availability"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: "sypialnia_motion_illuminance"
  state_topic: "zigbee2mqtt/0x00158d0001e55705"
  availability_topic: "zigbee2mqtt/0x00158d0001e55705/availability"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: "janek_motion_illuminance"
  state_topic: "zigbee2mqtt/0x00158d0001e5d112"
  availability_topic: "zigbee2mqtt/0x00158d0001e5d112/availability"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: "korytarz_motion_illuminance"
  state_topic: "zigbee2mqtt/0x00158d000237ad9d"
  availability_topic: "zigbee2mqtt/0x00158d000237ad9d/availability"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: "lazienka_motion_battery"
  state_topic: "zigbee2mqtt/0x00158d0001e0a7d3"
  availability_topic: "zigbee2mqtt/0x00158d0001e0a7d3/availability"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "sypialnia_motion_battery"
  state_topic: "zigbee2mqtt/0x00158d0001e55705"
  availability_topic: "zigbee2mqtt/0x00158d0001e55705/availability"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "janek_motion_battery"
  state_topic: "zigbee2mqtt/0x00158d0001e5d112"
  availability_topic: "zigbee2mqtt/0x00158d0001e5d112/availability"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "korytarz_motion_battery"
  state_topic: "zigbee2mqtt/0x00158d000237ad9d"
  availability_topic: "zigbee2mqtt/0x00158d000237ad9d/availability"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"
