- platform: "mqtt"
  name: "0x00158d0001e0a7d3_illuminance"
  state_topic: "zigbee2mqtt/0x00158d0001e0a7d3"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"
  json_attributes:
  - "linkquality"
  - "battery"
  - "voltage"
- platform: "mqtt"
  name: "0x00158d0001e55705_illuminance"
  state_topic: "zigbee2mqtt/0x00158d0001e55705"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"
  json_attributes:
  - "linkquality"
  - "battery"
  - "voltage"
- platform: "mqtt"
  name: "0x00158d0001e5d112_illuminance"
  state_topic: "zigbee2mqtt/0x00158d0001e5d112"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"
  json_attributes:
  - "linkquality"
  - "battery"
  - "voltage"

- platform: "mqtt"
  name: "0x00158d000237ad9d_illuminance"
  state_topic: "zigbee2mqtt/0x00158d000237ad9d"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"
  json_attributes:
  - "linkquality"
  - "battery"
  - "voltage"
