- platform: mqtt
  name: 'Roleta Kuchnia power'
  state_topic: 'shellies/shellyswitch-135303/relay/power'
  unit_of_measurement: 'W'
- platform: mqtt
  name: 'Roleta pokój Janka power'
  state_topic: 'shellies/shellyswitch-5B28DA/relay/power'
  unit_of_measurement: 'W'
- platform: mqtt
  name: 'Roleta Sypialnia power'
  state_topic: 'shellies/shellyswitch-32B580/relay/power'
  unit_of_measurement: 'W'
- platform: mqtt
  name: 'Roleta Salon power'
  state_topic: 'shellies/shellyswitch25-B94328/relay/power'
  unit_of_measurement: 'W'

- platform: mqtt
  name: 'Światło Kuchnia power'
  state_topic: 'shellies/shellyswitch-55A0C8/relay/power'
  unit_of_measurement: 'W'
