- platform: "mqtt"
  name: "kuchnia_smoke_battery"
  state_topic: "zigbee2mqtt/0x00158d0002b0b23f"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"
