- platform: mqtt
  name: "Swiatło Pokoj Janka Version"
  state_topic: "shellies/shelly_1/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"
- platform: mqtt
  name: "Lampa Salon Version"
  state_topic: "shellies/sonoff_lampa_salon/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"
- platform: mqtt
  name: "Salon regał Version"
  state_topic: "shellies/salon_regal/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"
- platform: mqtt
  name: "Swiatło Sypialnia Version"
  state_topic: "shellies/shelly_4/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"
#- platform: mqtt
#  name: "Swiatło TODO5 Version"
#  state_topic: "shellies/shelly_5/STATUS2"
#  value_template: "{{ value_json['StatusFWR'].Version }}"
#- platform: mqtt
#  name: "Kamera Version"
#  state_topic: "basic/sonoff-basic-3/STATUS2"
#  value_template: "{{ value_json['StatusFWR'].Version }}"
- platform: mqtt
  name: "Listwa RTV Version"
  state_topic: "listwa/listwa1/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"
- platform: mqtt
  name: "Listwa Sypialnia Version"
  state_topic: "zigbee2mqtt/sonoff1/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"
- platform: mqtt
  name: "Zmietek Version"
  state_topic: "zigbee2mqtt/sonoff4/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"
- platform: mqtt
  name: "Rtv Jan Version"
  state_topic: "basic/sonoff-rtv-jan/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"
- platform: mqtt
  name: "Pralka Version"
  state_topic: "zigbee2mqtt/powr2_1/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"
- platform: mqtt
  name: "Zmywarka Version"
  state_topic: "zigbee2mqtt/powr2_2/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"
