- platform: "mqtt"
  name: "0x00158d00022cc215_temperature"
  state_topic: "zigbee2mqtt/0x00158d00022cc215"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_template: "{{ value_json.temperature }}"
  json_attributes:
  - "linkquality"
  - "battery"
  - "voltage"

- platform: "mqtt"
  name: "0x00158d00022cc215_humidity"
  state_topic: "zigbee2mqtt/0x00158d00022cc215"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "humidity"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
  - "linkquality"
  - "battery"
  - "voltage"

- platform: "mqtt"
  name: "0x00158d00022cc215_pressure"
  state_topic: "zigbee2mqtt/0x00158d00022cc215"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  device_class: "pressure"
  value_template: "{{ value_json.pressure }}"
  json_attributes:
  - "linkquality"
  - "battery"
  - "voltage"
- platform: "mqtt"
  name: "0x00158d000272fe71_temperature"
  state_topic: "zigbee2mqtt/0x00158d000272fe71"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_template: "{{ value_json.temperature }}"
  json_attributes:
    - "linkquality"
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: "0x00158d000272fe71_humidity"
  state_topic: "zigbee2mqtt/0x00158d000272fe71"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "humidity"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "linkquality"
    - "battery"
    - "voltage"

- platform: "mqtt"
  name: "0x00158d000272fe71_pressure"
  state_topic: "zigbee2mqtt/0x00158d000272fe71"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  device_class: "pressure"
  value_template: "{{ value_json.pressure }}"
  json_attributes:
    - "linkquality"
    - "battery"
    - "voltage"
