- platform: "mqtt"
  name: "korytarz_temp_temperature"
  state_topic: "zigbee2mqtt/0x00158d00022cc215"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_template: "{{ value_json.temperature }}"

- platform: "mqtt"
  name: "korytarz_temp_humidity"
  state_topic: "zigbee2mqtt/0x00158d00022cc215"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "humidity"
  value_template: "{{ value_json.humidity }}"

- platform: "mqtt"
  name: "korytarz_temp_pressure"
  state_topic: "zigbee2mqtt/0x00158d00022cc215"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  device_class: "pressure"
  value_template: "{{ value_json.pressure }}"

- platform: "mqtt"
  name: "korytarz_temp_battery"
  state_topic: "zigbee2mqtt/0x00158d00022cc215"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "kuchnia_temp_temperature"
  state_topic: "zigbee2mqtt/0x00158d000272fe71"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_template: "{{ value_json.temperature }}"

- platform: "mqtt"
  name: "kuchnia_temp_humidity"
  state_topic: "zigbee2mqtt/0x00158d000272fe71"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "humidity"
  value_template: "{{ value_json.humidity }}"

- platform: "mqtt"
  name: "kuchnia_temp_pressure"
  state_topic: "zigbee2mqtt/0x00158d000272fe71"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  device_class: "pressure"
  value_template: "{{ value_json.pressure }}"

- platform: "mqtt"
  name: "kuchnia_temp_battery"
  state_topic: "zigbee2mqtt/0x00158d000272fe71"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"
