- platform: rest
  scan_interval: 86400
  name: Sonoff Firmware Version
  resource: https://api.github.com/repos/arendst/Sonoff-Tasmota/releases/latest
  value_template: '{{ value_json.tag_name }}'
  headers:
    Accept: application/vnd.github.v3+json
    Content-Type: application/json
    User-Agent: Home Assistant REST sensor
