- platform: rest
  resource: https://pypi.org/pypi/homeassistant/json
  name: Home assistant version
  value_template: '{{ value_json.info.version }}'
  scan_interval: 3600

- platform: rest
  scan_interval: 21600
  name: Sonoff Firmware Version
  resource: https://api.github.com/repos/arendst/Sonoff-Tasmota/releases/latest
  value_template: '{{ value_json.tag_name }}'
  headers:
    Accept: application/vnd.github.v3+json
    Content-Type: application/json
    User-Agent: Home Assistant REST sensor
