- platform: rest
  resource: https://pypi.org/pypi/homeassistant/json
  name: Home assistant version
  value_template: '{{ value_json.info.version }}'
  scan_interval: 3600

- platform: command_line
  name: Sonoff Firmware Version
  command: 'curl -s https://github.com/arendst/Sonoff-Tasmota/releases/latest | cut -d\" -f2 | rev | cut -d/ -f1 | rev 2>/local/versionsonoffhtml.err'
  scan_interval: 21600
