- platform: template
  sensors:
    vacuum_status:
      value_template: "{{ states.vacuum.zmietekv2.attributes.status }}"
      friendly_name: "Status"
      entity_id: vacuum.zmietekv2
      icon_template: >-
        {% if is_state('sensor.vacuum_status', 'Cleaning') %}
          mdi:robot-vacuum
        {% elif is_state('sensor.vacuum_status', 'Returning home') %}
          mdi:home
        {% elif is_state('sensor.vacuum_status', 'Charging') %}
          mdi:battery-charging-wireless
        {% elif is_state('sensor.vacuum_status', 'Idle') %}
          mdi:sleep
        {% elif is_state('sensor.vacuum_status', 'Error') %}
          mdi:alert
        {% elif is_state('sensor.vacuum_status', 'Charger disconnected') %}
          mdi:power-plug-off
        {% else %}
          mdi:help-circle
        {% endif %}
    vacuum_fan:
      value_template: "{{ states.vacuum.zmietekv2.attributes.fan_speed }}"
      friendly_name: "Fan"
      entity_id: vacuum.zmietekv2
      icon_template: mdi:fan
    vacuum_cleaned_area:
      value_template: "{{ states.vacuum.zmietekv2.attributes.cleaned_area }}"
      friendly_name: "Cleaned area"
      unit_of_measurement: "m2"
      entity_id: vacuum.zmietekv2
      icon_template: mdi:broom
    vacuum_battery:
      value_template: "{{ states.vacuum.zmietekv2.attributes.battery_level }}"
      friendly_name: "Battery"
      entity_id: vacuum.zmietekv2
      unit_of_measurement: "%"
      icon_template: mdi:battery
    vacuum_cleaning_time:
      value_template: "{{ states.vacuum.zmietekv2.attributes.cleaning_time }}"
      friendly_name: "Cleaning time"
      entity_id: vacuum.zmietekv2
      icon_template: mdi:timer
    vacuum_main_brush:
      friendly_name: "Main Brush Left"
      unit_of_measurement: "Hrs"
      value_template: "{{ states.vacuum.zmietekv2.attributes.main_brush_left }}"
    vacuum_side_brush:
      friendly_name: "Side Brush Left"
      unit_of_measurement: "Hrs"
      value_template: "{{ states.vacuum.zmietekv2.attributes.side_brush_left }}"
    vacuum_filter:
      friendly_name: "Filter Left"
      unit_of_measurement: "Hrs"
      value_template: "{{ states.vacuum.zmietekv2.attributes.filter_left }}"
    vacuum_cleaning_count:
      friendly_name: "Cleaning Count"
      value_template: "{{ states.vacuum.zmietekv2.attributes.cleaning_count }}"
