- alias: 'Home for 8 minutes'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.80b03dcda5eb
      to: home
      for:
        minutes: 8
    - platform: state
      entity_id: device_tracker.e49a79e25678
      to: home
      for:
        minutes: 8
  condition:
    - condition: sun
      after: sunrise
    - condition: sun
      before: sunset
      before_offset: '02:00:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.just_returned_home
    - service: input_select.select_option
      data:
        entity_id: input_select.presence_status
        option: Home
