alias: "Left home"
trigger:
  - platform: state
    entity_id: group.all_devices
    to: 'not_home'
condition:
  - condition: time
    before: '05:15:00'
    after: '05:20:00'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.just_returned_home
  - service: input_select.select_option
    data:
      entity_id: input_select.presence_status
      option: Just Left