- alias: 'Left home'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.home_occupied
      to: 'off'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.just_returned_home
    - service: input_select.select_option
      data:
        entity_id: input_select.presence_status
        option: 'Just Left'
