- alias: 'Left home'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.mobiledevices
      to: not_home
  condition:
    - condition: time
      after: '06:00:00'
      before: '23:59:59'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.just_returned_home
    - service: input_select.select_option
      data:
        entity_id: input_select.presence_status
        option: Just Left
