- alias: 'Left home - Set status'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.home_occupied
      to: 'off'
  condition:
    - condition: time
      after: '06:00:00'
      before: '23:59:59'
    - condition: state
      entity_id: input_boolean.just_returned_home
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.just_left