- alias: 'Home for 1 minute'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: person.zenedith
      to: 'home'
      for:
        minutes: 1
    - platform: state
      entity_id: person.kate
      to: 'home'
      for:
        minutes: 1
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.just_returned_home
    - service: input_select.select_option
      data:
        entity_id: input_select.presence_status
        option: 'Home'
