- alias: 'Home for 1 minute'
#  initial_state: 'on'
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.80b03dcda5eb
      to: 'home'
      for:
        minutes: 1
    - platform: state
      entity_id: device_tracker.e49a79e25678
      to: 'home'
      for:
        minutes: 1
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.just_returned_home
    - service: input_select.select_option
      data:
        entity_id: input_select.presence_status
        option: 'Home'
