- alias: 'Returned home - Set status'
  trigger:
    - platform: state
      entity_id: device_tracker.80b03dcda5eb
      to: home
      for:
        minutes: 8
    - platform: state
      entity_id: device_tracker.e49a79e25678
      to: home
      for:
        minutes: 8
  condition:
    - condition: state
      entity_id: input_boolean.just_left
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.just_returned_home
