- alias: 'Returned home - Set status'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: person.zenedith
      to: 'home'
      for:
        minutes: 1
    - platform: state
      entity_id: person.kate
      to: 'home'
      for:
        minutes: 1
  condition:
    - condition: time
      after: '06:00:00'
      before: '23:59:59'
    - condition: state
      entity_id: input_boolean.just_left
      state: 'off'
    - condition: state
      entity_id: input_boolean.just_returned_home
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.just_returned_home
