- platform: "mqtt"
  name: "drzwi_balkonowe_contact"
  state_topic: "zigbee2mqtt/0x00158d000205b35f"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"

- platform: "mqtt"
  name: "drzwi_wejsciowe_contact"
  state_topic: "zigbee2mqtt/0x00158d00020b7b77"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"

- platform: "mqtt"
  name: "okno_janek_contact"
  state_topic: "zigbee2mqtt/0x00158d000208e0c7"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"

- platform: "mqtt"
  name: "okno_sypialnia_contact"
  state_topic: "zigbee2mqtt/0x00158d0002bfd324"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"

- platform: "mqtt"
  name: "drzwi_lazienka_contact"
  state_topic: "zigbee2mqtt/0x00158d00024e42b5"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"

- platform: "mqtt"
  name: "drzwi_toaleta_contact"
  state_topic: "zigbee2mqtt/0x00158d0002b52fd0"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"

- platform: "mqtt"
  name: "okno_kuchnia_contact"
  state_topic: "zigbee2mqtt/0x00158d00032169f8"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: false
  payload_off: true
  value_template: "{{ value_json.contact }}"
  device_class: "door"
