- platform: "mqtt"
  name: "kuchnia_leak_water_leak"
  state_topic: "zigbee2mqtt/0x00158d00021508b4"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.water_leak }}"
  device_class: "moisture"

- platform: "mqtt"
  name: "lazienka_leak_water_leak"
  state_topic: "zigbee2mqtt/0x00158d0001bb388f"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.water_leak }}"
  device_class: "moisture"
