- platform: "mqtt"
  name: "0x00158d0001e0a7d3_occupancy"
  state_topic: "zigbee2mqtt/0x00158d0001e0a7d3"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"
  json_attributes:
  - "linkquality"
  - "battery"
  - "voltage"
- platform: "mqtt"
  name: "0x00158d0001e55705_occupancy"
  state_topic: "zigbee2mqtt/0x00158d0001e55705"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"
  json_attributes:
  - "linkquality"
  - "battery"
  - "voltage"
- platform: "mqtt"
  name: "0x00158d0001e5d112_occupancy_2"
  state_topic: "zigbee2mqtt/0x00158d0001e5d112"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"
  json_attributes:
  - "linkquality"
  - "battery"
  - "voltage"
