- platform: "mqtt"
  name: "lazienka_motion_occupancy"
  state_topic: "zigbee2mqtt/0x00158d0001e0a7d3"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"

- platform: "mqtt"
  name: "sypialnia_motion_occupancy"
  state_topic: "zigbee2mqtt/0x00158d0001e55705"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"

- platform: "mqtt"
  name: "janek_motion_occupancy"
  state_topic: "zigbee2mqtt/0x00158d0001e5d112"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"

- platform: "mqtt"
  name: "korytarz_motion_occupancy"
  state_topic: "zigbee2mqtt/0x00158d000237ad9d"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.occupancy }}"
  device_class: "motion"
