- platform: ping
  name: zen_pc_online
  host: 192.168.1.2
  count: 2
  scan_interval: 60

- platform: ping
  name: dafang_online
  host: 192.168.1.127
  count: 1
  scan_interval: 30

- platform: ping
  name: ambient-regal_online
  host: 192.168.1.112
  count: 2
  scan_interval: 60

- platform: ping
  name: ambient-obraz_online
  host: 192.168.1.23
  count: 2
  scan_interval: 60

- platform: ping
  name: salon_regal_switch_online
  host: 192.168.1.11
  count: 2
  scan_interval: 60

- platform: ping
  name: yeelink-light-ceil_online
  host: 192.168.1.22
  count: 2
  scan_interval: 60

- platform: ping
  name: shelly_1_pokoj_jan_online
  host: 192.168.1.24
  count: 2
  scan_interval: 60

- platform: ping
  name: yeelink-light-ceil_online
  host: 192.168.1.25
  count: 2
  scan_interval: 60

- platform: ping
  name: sonoff-rtv-jan-270_online
  host: 192.168.1.29
  count: 2
  scan_interval: 60

- platform: ping
  name: lampa-kuchnia-2_online
  host: 192.168.1.34
  count: 2
  scan_interval: 60

- platform: ping
  name: listwa-sypialnia_online
  host: 192.168.1.37
  count: 2
  scan_interval: 60

- platform: ping
  name: zmietek_switch_online
  host: 192.168.1.38
  count: 2
  scan_interval: 60
##
- platform: ping
  name: sharp_online
  host: 192.168.1.39
  count: 2
  scan_interval: 60
#
- platform: ping
  name: lampa-korytarz-drzwi_online
  host: 192.168.1.63
  count: 2
  scan_interval: 60

- platform: ping
  name: Chromecast-pokoj_janka_online
  host: 192.168.1.64
  count: 2
  scan_interval: 60

- platform: ping
  name: Zenedith_macbook_online
  host: 192.168.1.67
  count: 2
  scan_interval: 60

- platform: ping
  name: lampa-kuchnia-3_online
  host: 192.168.1.69
  count: 2
  scan_interval: 60

- platform: ping
  name: sonoff_lampa_salon_online
  host: 192.168.1.91
  count: 2
  scan_interval: 60

- platform: ping
  name: bedside_online
  host: 192.168.1.115
  count: 2
  scan_interval: 60

- platform: ping
  name: listwa-salon_online
  host: 192.168.1.125
  count: 2
  scan_interval: 60

- platform: ping
  name: roleta-kuchnia_online
  host: 192.168.1.129
  count: 2
  scan_interval: 60

- platform: ping
  name: roborock_online
  host: 192.168.1.133
  count: 2
  scan_interval: 60

- platform: ping
  name: shelly_4_sypialnia_online
  host: 192.168.1.135
  count: 2
  scan_interval: 60

- platform: ping
  name: roleta-sypialnia_online
  host: 192.168.1.141
  count: 2
  scan_interval: 60

- platform: ping
  name: yeelink-light-lamp_online
  host: 192.168.1.150
  count: 2
  scan_interval: 60

- platform: ping
  name: shelly1-toaleta_online
  host: 192.168.1.156
  count: 2
  scan_interval: 60

- platform: ping
  name: NOVA_online
  host: 192.168.1.157
  count: 2
  scan_interval: 60

- platform: ping
  name: hassbian3_online
  host: 192.168.1.162
  count: 2
  scan_interval: 60

- platform: ping
  name: RMMINI_online
  host: 192.168.1.163
  count: 2
  scan_interval: 60

- platform: ping
  name: roleta-pokoj-janka_online
  host: 192.168.1.168
  count: 2
  scan_interval: 60

- platform: ping
  name: lampa-kuchnia-1_online
  host: 192.168.1.181
  count: 2
  scan_interval: 60

- platform: ping
  name: lampa-korytarz_online
  host: 192.168.1.223
  count: 2
  scan_interval: 60
