- alias: 'Auto chillout Jas on'
  trigger:
    platform: time
    at: '21:30:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.jasiu_chillout

- alias: 'Auto chillout Sypialnia on'
  trigger:
    platform: time
    at: '23:30:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sypialnia_chillout

- alias: 'Auto chillout off'
  trigger:
    platform: time
    at: '06:01:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.jasiu_chillout
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sypialnia_chillout
