- alias: 'korytarz ambilight on'
  initial_state: 'on'
  trigger:
    platform: time
    at: '20:30:00'
  condition:
    - condition: state
      entity_id: binary_sensor.home_occupied
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.lampa_korytarz_ambilight
      data_template:
        brightness: 1

- alias: 'korytarz automations off'
  initial_state: 'on'
  trigger:
    platform: time
    at: '21:30:00'
  action:
    - service: automation.turn_off
      data:
        entity_id: automation.wlacz_swiatlo_w_korytarzu_gdy_ruch,automation.wlacz_swiatlo_w_pokoju_janka_gdy_ruch

- alias: 'korytarz ambilight off'
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: light.turn_off
      entity_id: light.lampa_korytarz_ambilight
    - service: automation.turn_on
      data:
        entity_id: automation.wlacz_swiatlo_w_korytarzu_gdy_ruch,automation.wlacz_swiatlo_w_pokoju_janka_gdy_ruch

- alias: 'Auto chillout Jas on'
  initial_state: 'on'
  trigger:
    platform: time
    at: '21:29:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.jasiu_chillout

- alias: 'Auto chillout Sypialnia on'
  initial_state: 'on'
  trigger:
    platform: time
    at: '21:29:15'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sypialnia_chillout

- alias: 'Auto chillout off'
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:20:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.moonlight_korytarz
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.jasiu_chillout
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sypialnia_chillout
    - service: light.turn_on
      entity_id: group.kuchnia_lampa
      data_template:
        brightness: 255

- alias: 'Chillout mode on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.jasiu_chillout
      to: 'on'
    - platform: state
      entity_id: input_boolean.sypialnia_chillout
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.moonlight_korytarz
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.moonlight_korytarz

- alias: 'Chillout mode off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.jasiu_chillout
      to: 'off'
    - platform: state
      entity_id: input_boolean.sypialnia_chillout
      to: 'off'
  condition:
    - condition: state
      entity_id: light.lampa_korytarz_drzwi
      state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.moonlight_korytarz

- alias: 'Chillout mode on when first time lights turn on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.lampa_korytarz_drzwi
      to: 'on'
  condition:
    - condition: state
      entity_id:  binary_sensor.lampa_korytarz_drzwi_nightlight
      state: 'off'
    - condition: state
      entity_id: input_boolean.moonlight_korytarz
      state: 'on'
  action:
    - service: script.moonlight_korytarz_on

- alias: 'Chillout mode off when first time lights turn on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.lampa_korytarz_drzwi
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.lampa_korytarz_drzwi_nightlight
      state: 'on'
    - condition: state
      entity_id: input_boolean.moonlight_korytarz
      state: 'off'
  action:
    - service: script.moonlight_korytarz_off

- alias: 'Moonlight switch on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.moonlight_korytarz
      to: 'on'
  condition:
    - condition: state
      entity_id: light.lampa_korytarz_drzwi
      state: 'on'
  action:
    - service: script.moonlight_korytarz_on

- alias: 'Moonlight switch off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.moonlight_korytarz
      to: 'off'
  condition:
    - condition: state
      entity_id: light.lampa_korytarz_drzwi
      state: 'on'
  action:
    - service: script.moonlight_korytarz_off

- alias: 'Moonlight kuchnia switch on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.moonlight_kuchnia
      to: 'on'
  condition:
    - condition: state
      entity_id: group.kuchnia_lampa
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: group.kuchnia_lampa
      data_template:
        brightness: 1

- alias: 'Moonlight kuchnia switch off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.moonlight_kuchnia
      to: 'off'
  condition:
    - condition: state
      entity_id: group.kuchnia_lampa
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: group.kuchnia_lampa
      data_template:
        brightness: 255
