- alias: Reminder - Refresh date countdown sensors
  trigger:
    - platform: time
      at: '00:00:01'
    - platform: homeassistant
      event: start
  action:
    - service: python_script.date_countdown
      data:
        name: Kasia
        type: birthday
        date: 20/11/1982
    - service: python_script.date_countdown
      data:
        name: Jan
        type: birthday
        date: 28/05/2015
    - service: python_script.date_countdown
      data:
        name: Our wedding
        type: anniversary
        date: 18/07/2009
