
- alias: 'Climate off when ogrzewanie switch off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.ogrzewanie
      to: 'off'
  action:
    - service: script.climate_off
    - service: automation.turn_off
      data:
        entity_id:
          - automation.przykrec_ogrzewanie_po_powrocie_przy_nadal_otwartych_drzwiach_w_salonie
          - automation.przykrec_ogrzewanie_po_powrocie_przy_nadal_otwartym_oknie_w_pokoju_janka
          - automation.przykrec_ogrzewanie_po_powrocie_przy_nadal_otwartym_oknie_w_sypialni
          - automation.przykrec_ogrzewanie_przy_otwartych_drzwiach_w_salonie
          - automation.przykrec_ogrzewanie_przy_otwartym_oknie_w_pokoju_janka
          - automation.przykrec_ogrzewanie_przy_otwartym_oknie_w_sypialni
          - automation.przywroc_ogrzewanie_przy_zamknietych_drzwiach_w_salonie
          - automation.przywroc_ogrzewanie_przy_zamknietym_oknie_w_pokoju_janka
          - automation.przywroc_ogrzewanie_przy_zamknietym_oknie_w_sypialni

- alias: 'Climate on when ogrzewanie switch on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.ogrzewanie
      to: 'on'
  action:
    - service: script.climate_turn_on
    - service: automation.turn_on
      data:
        entity_id:
          - automation.przykrec_ogrzewanie_po_powrocie_przy_nadal_otwartych_drzwiach_w_salonie
          - automation.przykrec_ogrzewanie_po_powrocie_przy_nadal_otwartym_oknie_w_pokoju_janka
          - automation.przykrec_ogrzewanie_po_powrocie_przy_nadal_otwartym_oknie_w_sypialni
          - automation.przykrec_ogrzewanie_przy_otwartych_drzwiach_w_salonie
          - automation.przykrec_ogrzewanie_przy_otwartym_oknie_w_pokoju_janka
          - automation.przykrec_ogrzewanie_przy_otwartym_oknie_w_sypialni
          - automation.przywroc_ogrzewanie_przy_zamknietych_drzwiach_w_salonie
          - automation.przywroc_ogrzewanie_przy_zamknietym_oknie_w_pokoju_janka
          - automation.przywroc_ogrzewanie_przy_zamknietym_oknie_w_sypialni
