- alias: 'dafang motion detected'
  trigger:
    payload: 'ON'
    platform: mqtt
    topic: camera/dafang/motion
  condition:
    - condition: state
      entity_id: group.mobiledevices
      state: not_home
  action:
    service: notify.mypushbullet
    data_template:
      title: '!! Security kamera !!'
      message: |
        {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
        Wykryto ruch.
