- alias: 'dafang motion detected'
  trigger:
    payload: 'ON'
    platform: mqtt
    topic: camera/dafang/motion
  action:
    service: notify.mypushbullet
    data_template:
      title: 'Security kamera'
      message: |
        {{now().strftime("%a %b %d %H:%M:%S %p")}}
        Wykryto ruch.
