- alias: 'dafang motion detected'
  trigger:
    payload: 'ON'
    platform: mqtt
    topic: camera/dafang/motion
  action:
    service: notify.mypushbullet
    data:
      title: "Security"
      message: "Motion detected."
