- alias: 'Everything off when gone'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.presence_status
      to: 'Away'
  action:
    - service: script.everything_off
