- alias: 'Everything off when gone'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.presence_status
      to: 'Away'
  action:
    - service: script.everything_off
    - service: notify.mypushbullet
      data_template:
        title: 'Away home'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Wszyscy poza domem - wylacz wszystko.
