- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "zigbee2mqtt/sonoff2/cmnd/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "zigbee2mqtt/sonoff1/cmnd/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "basic/sonoff-basic-3/cmnd/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "zigbee2mqtt/sonoff4/cmnd/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "zigbee2mqtt/sonoff5/cmnd/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "zigbee2mqtt/powr2_1/cmnd/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "incan/incan1/cmnd/POWER1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "incan/incan1/cmnd/POWER2"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "incan/incan2/cmnd/POWER1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "incan/incan2/cmnd/POWER2"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "incan/incan3/cmnd/POWER1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "incan/incan3/cmnd/POWER2"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "incan/incan4/cmnd/POWER1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "incan/incan4/cmnd/POWER2"
        payload: ""

- alias: "Update notifications"
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.mypushbullet
      data_template:
        title: 'New Home Assistant Release'
        message: "Home Assistant  {{ states.updater.updater.state }}  is now available."
