- alias: 'Power state on HA start up'
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/sonoff2/cmnd/POWER'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'listwa/listwa1/cmnd/POWER1'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'listwa/listwa1/cmnd/POWER2'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'listwa/listwa1/cmnd/POWER3'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'listwa/listwa1/cmnd/POWER4'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'listwa/listwa1/cmnd/POWER5'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'basic/sonoff-rtv-jan/cmnd/POWER'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/sonoff1/cmnd/POWER'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'basic/sonoff-basic-3/cmnd/POWER'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/sonoff4/cmnd/POWER'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/sonoff5/cmnd/POWER'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/powr2_1/cmnd/POWER'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/powr2_2/cmnd/POWER'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'incan/incan1/cmnd/POWER1'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'incan/incan1/cmnd/POWER2'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'incan/incan2/cmnd/POWER1'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'incan/incan2/cmnd/POWER2'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'incan/incan3/cmnd/POWER1'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'incan/incan3/cmnd/POWER2'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'incan/incan4/cmnd/POWER1'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'incan/incan4/cmnd/POWER2'
        payload: ""
    - service: mqtt.publish
      data:
        topic: 'shellies/shellyswitch-32B580/online'
        payload: 'true'
    - service: mqtt.publish
      data:
        topic: 'shellies/shellyswitch-5B28DA/online'
        payload: 'true'
    - service: mqtt.publish
      data:
        topic: 'shellies/shellyswitch-135303/online'
        payload: 'true'
    - service: mqtt.publish
      data:
        topic: 'shellies/shellyswitch-55A0C8/online'
        payload: 'true'
    - service: mqtt.publish
      data:
        topic: 'shellies/shelly1-25A3EB/online'
        payload: 'true'
    - service: mqtt.publish
      data:
        topic: 'shellies/shelly_1/online'
        payload: 'true'
    - service: mqtt.publish
      data:
        topic: 'shellies/sonoff_lampa_salon/online'
        payload: 'true'
    - service: mqtt.publish
      data:
        topic: 'shellies/salon_regal/online'
        payload: 'true'
    - service: mqtt.publish
      data:
        topic: 'shellies/shelly_4/online'
        payload: 'true'
    - service: mqtt.publish
      data:
        topic: 'shellies/shelly_5/online'
        payload: 'true'

- alias: 'Update notifications'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.mypushbullet
      data_template:
        title: 'New Home Assistant Release'
        message: |
          {{now().strftime('%d.%m.%Y-%H:%M:%S')}}
          Home Assistant {{ states.updater.updater.state }} is now available.
