- alias: 'Everything off when gone'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.presence_status
      to: 'Away'
  condition:
    - condition: sun
      after: sunrise
      after_offset: '-02:00:00'
    - condition: sun
      before: sunset
      before_offset: '02:00:00'
  action:
    - service: script.everything_off
    - service: notify.mypushbullet
      data_template:
        title: 'Away home'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Wszyscy poza domem - wylacz wszystko.

- alias: 'Rolety close when gone'
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: input_select.presence_status
      to: 'Away'
  condition:
    - condition: numeric_state
      entity_id: sensor.dark_sky_temperature
      above: 26
    - condition: sun
      after: sunrise
    - condition: sun
      before: sunset
      before_offset: '-01:00:00'
  action:
    - service: script.rolety_close
    - service: notify.mypushbullet
      data_template:
        title: 'Rolety close when gone'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Rolety close when gone.

- alias: 'Climate off when gone'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.presence_status
      to: 'Away'
  condition:
    - condition: state
      entity_id: input_boolean.ogrzewanie
      state: 'on'
    - condition: sun
      after: sunrise
      after_offset: '-02:00:00'
    - condition: sun
      before: sunset
      before_offset: '02:00:00'
  action:
    - service: script.climate_off
    - service: notify.mypushbullet
      data_template:
        title: 'Climate off when gone'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Climate off when gone.

- alias: 'Zmietek start when gone 15 min delay'
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: input_select.presence_status
      to: 'Away'
      for:
        minutes: 15
  condition:
    - condition: sun
      after: sunrise
    - condition: sun
      before: sunset
      before_offset: '-02:00:00'
  action:
    - service: script.zmietek_start
