- alias: 'Rolety open when home'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.presence_status
      to: 'Home'
  condition:
    - condition: sun
      before: sunset
      before_offset: '02:00:00'
    - condition: sun
      after: sunrise
  action:
    - service: script.rolety_open
