- alias: 'Rolety open when home'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.presence_status
      to: 'Home'
  condition:
    - condition: time
      after: '07:00:00'
      before: '19:00:00'
  action:
    - service: script.rolety_open
