- alias: 'Sleep mode for air purifier'
  initial_state: 'on'
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    - condition: state
      entity_id: fan.purifier
      state: 'on'
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.purifier
        speed: 'Silent'

- alias: 'Sleep mode for humidifier'
  initial_state: 'on'
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    - condition: state
      entity_id: fan.smartmi2
      state: 'on'
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.smartmi2
        speed: 'Silent'

- alias: 'Auto mode for air purifier'
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    - condition: state
      entity_id: fan.purifier
      state: 'on'
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.purifier
        speed: 'Auto'

- alias: 'Auto mode for humidifier'
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    - condition: state
      entity_id: fan.smartmi2
      state: 'on'
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.smartmi2
        speed: 'Auto'

- alias: 'Power off humidifier when no water'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.humidifier_depth
      below: 10
  condition:
    - condition: state
      entity_id: fan.smartmi2
      state: 'on'
  action:
    - service: fan.turn_off
      data:
        entity_id: fan.smartmi2
    - service: notify.mypushbullet
      data_template:
        title: 'Humidifier off, no water'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Humidifier off, no water

- alias: 'Power off humidifier when humidity above 50%'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.korytarz_temp_humidity
      above: 50
  condition:
    - condition: state
      entity_id: fan.smartmi2
      state: 'on'
  action:
    - service: fan.turn_off
      data:
        entity_id: fan.smartmi2
    - service: notify.mypushbullet
      data_template:
        title: 'Humidifier off humidity > 50%'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Humidifier off humidity > 50%

- alias: 'Power on humidifier when humidity below 35%'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.korytarz_temp_humidity
    below: 35
  condition:
    - condition: state
      entity_id: fan.smartmi2
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.humidifier_depth
      above: 15
  action:
    - service: fan.turn_on
      data:
        entity_id: fan.smartmi2
    - service: notify.mypushbullet
      data_template:
        title: 'Humidifier on humidity < 35%'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Humidifier on humidity < 35 %

- alias: 'Power off purifier when aqi below 5'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.purifier_aqi
      below: 5
  condition:
    - condition: state
      entity_id: fan.purifier
      state: 'on'
  action:
    - service: fan.turn_off
      data:
        entity_id: fan.purifier
    - service: notify.mypushbullet
      data_template:
        title: 'Purifier off aqi < 5'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Purifier off aqi < 5

- alias: 'Power on purifier when aqi above 15'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.purifier_aqi
    above: 15
  condition:
    - condition: state
      entity_id: fan.purifier
      state: 'off'
  action:
    - service: fan.turn_on
      data:
        entity_id: fan.purifier
    - service: notify.mypushbullet
      data_template:
        title: 'Purifier on aqi > 15'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Purifier off aqi > 15