- alias: 'Sleep mode for air purifier'
  initial_state: 'on'
  trigger:
    platform: time
    at: '23:00:00'
  condition:
    - condition: state
      entity_id: fan.purifier
      state: 'on'
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.purifier
        speed: 'silent'

- alias: 'Sleep mode for humidifier'
  initial_state: 'on'
  trigger:
    platform: time
    at: '23:00:00'
  condition:
    - condition: state
      entity_id: fan.smartmi2
      state: 'on'
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.smartmi2
        speed: 'silent'

- alias: 'Auto mode for air purifier'
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:01:00'
  condition:
    - condition: state
      entity_id: fan.purifier
      state: 'on'
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.purifier
        speed: 'auto'

- alias: 'Auto mode for humidifier'
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:01:00'
  condition:
    - condition: state
      entity_id: fan.smartmi2
      state: 'on'
  action:
    - service: fan.set_speed
      data:
        entity_id: fan.smartmi2
        speed: 'auto'

- alias: 'Power off humidifier when no water'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.humidifier_depth
      below: 5
  condition:
    - condition: state
      entity_id: fan.smartmi2
      state: 'on'
  action:
    - service: fan.turn_off
      data:
        entity_id: fan.smartmi2
    - service: notify.mypushbullet
      data_template:
        title: 'Humidifier off, no water'
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          Humidifier off, no water

- alias: 'Power off humidifier when humidity above 60%'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.korytarz_temp_humidity
      above: 60
  condition:
    - condition: state
      entity_id: fan.smartmi2
      state: 'on'
  action:
    - service: fan.turn_off
      data:
        entity_id: fan.smartmi2
#    - service: notify.mypushbullet
#      data_template:
#        title: 'Humidifier off humidity > 60%'
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Humidifier off humidity > 60%

- alias: 'Power on humidifier when humidity below 45%'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.korytarz_temp_humidity
    below: 45
  condition:
    - condition: state
      entity_id: fan.smartmi2
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.humidifier_depth
      above: 10
  action:
    - service: fan.turn_on
      data:
        entity_id: fan.smartmi2
#    - service: notify.mypushbullet
#      data_template:
#        title: 'Humidifier on humidity < 45%'
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Humidifier on humidity < 45 %

- alias: 'Purifier sleep mode when aqi below 8'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.purifier_aqi
      below: 8
  condition:
    - condition: template
      value_template: "{{ not is_state('sensor.purifier_mode', 'silent') }}"
  action:
    - service: fan.turn_on
      data:
        entity_id: fan.purifier
    - service: fan.set_speed
      data:
        entity_id: fan.purifier
        speed: 'silent'
#    - service: notify.mypushbullet
#      data_template:
#        title: 'Purifier sleep mode aqi < 8'
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Purifier sleep mode aqi < 8

- alias: 'Purifier full power when aqi above 15'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.purifier_aqi
    above: 15
  condition:
    - condition: template
      value_template: "{{ not is_state('sensor.purifier_mode', 'favorite') }}"
    - condition: time
      after: '08:00:00'
      before: '21:30:00'
  action:
    - service: fan.turn_on
      data:
        entity_id: fan.purifier
    - service: fan.set_speed
      data:
        entity_id: fan.purifier
        speed: 'Favorite'
#    - service: notify.mypushbullet
#      data_template:
#        title: 'Purifier full power when aqi above 15'
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Purifier full power when aqi above 15

- alias: 'Purifier and humidifier off when wietrzenie start'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.wietrzenie
    to: 'on'
  action:
    - service: fan.turn_off
      data:
        entity_id: fan.purifier,fan.smartmi2
    - service: automation.turn_off
      data:
        entity_id: automation.purifier_full_power_when_aqi_above_15, automation.purifier_sleep_mode_when_aqi_below_8, automation.power_off_humidifier_when_humidity_above_60, automation.power_on_humidifier_when_humidity_below_45
#    - service: notify.mypushbullet
#      data_template:
#        title: 'Purifier and humidifier automations off'
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Purifier and humidifier automations off

- alias: 'Purifier on when wietrzenie end'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.wietrzenie
    to: 'off'
  action:
    - service: fan.turn_on
      data:
        entity_id: fan.purifier
    - service: automation.turn_on
      data:
        entity_id: automation.purifier_full_power_when_aqi_above_15, automation.purifier_sleep_mode_when_aqi_below_8, automation.power_off_humidifier_when_humidity_above_60, automation.power_on_humidifier_when_humidity_below_45
#    - service: notify.mypushbullet
#      data_template:
#        title: 'Purifier automations on'
#        message: |
#          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
#          Purifier automations on
