- alias: 'Rolety pokoje open at 12'
  initial_state: 'on'
  trigger:
    platform: time
    at: '12:00:00'
  action:
    - service: cover.open_cover
      data:
        entity_id: cover.pokoj_janka, cover.sypialnia

- alias: 'Roleta w kuchni 60% o 17'
  initial_state: 'on'
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    - condition: state
      entity_id: cover.kuchnia
      state: 'open'
  action:
    - service: mqtt.publish
      data_template:
        topic: 'shellies/shellyswitch-135303/roller/0/command/pos'
        retain: false
        payload: '60'
