- alias: 'Rpi power problem notification'
  trigger:
    - platform: numeric_state
      entity_id: sensor.rpi_power_status
      value_template: '{{ state.attributes.value }}'
      above: 0
      for:
        minutes: 5
  action:
    - service: notify.mypushbullet
      data_template:
        title: Power Supply Issue
        message: |
          {{now().strftime("%d.%m.%Y-%H:%M:%S")}}
          RPI Power reported {{ states.sensor.rpi_power_status.state }}.
          The state had changed from {{ trigger.from_state.state }}.
