- alias: 'Tasmota update check'
  trigger:
    platform: time
    at: '12:00:00'
  action:
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/sonoff2/cmnd/status'
        payload: "2"
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/sonoff1/cmnd/status'
        payload: "2"
    - service: mqtt.publish
      data:
        topic: 'basic/sonoff-basic-3/cmnd/status'
        payload: "2"
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/sonoff4/cmnd/status'
        payload: "2"
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/sonoff5/cmnd/status'
        payload: "2"
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/powr2_1/cmnd/status'
        payload: "2"
    - service: mqtt.publish
      data:
        topic: 'incan/incan1/cmnd/status'
        payload: "2"
    - service: mqtt.publish
      data:
        topic: 'incan/incan2/cmnd/status'
        payload: "2"
    - service: mqtt.publish
      data:
        topic: 'incan/incan3/cmnd/status'
        payload: "2"
    - service: mqtt.publish
      data:
        topic: 'incan/incan4/cmnd/status'
        payload: "2"
