- alias: 'Completed Torrent'
  trigger:
    platform: event
    event_type: transmission_downloaded_torrent
  action:
    - service: notify.mypushbullet
      data_template:
        title: "Torrent completed!"
        message: "{{trigger.event.data.name}}"
