title: Home all
views:
  - !include salon_view.yaml
  - !include korytarz_view.yaml
  - !include pokoj_janka_view.yaml
  - !include sypialnia_view.yaml
  - !include weather_view.yaml
#  - !include lazienka_view.yaml
  - !include security_view.yaml
#  - !include automation_view.yaml
  - !include system_status_view.yaml
  - !include battery_view.yaml
