title: Home
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.home_occupied
      - entity: binary_sensor.listwa_sypiania_used
      - entity: binary_sensor.rtv_used
      - entity: binary_sensor.yeelight_salon_3_online
      - entity: binary_sensor.listwa_sypialnia_online
      - entity: binary_sensor.ac_point_online
      - entity: binary_sensor.zmietek_switch_online
      - entity: binary_sensor.drzwi_wejsciowe_contact
      - entity: binary_sensor.kuchnia_smoke_detector
      - entity: binary_sensor.drzwi_lazienka_contact
      - entity: binary_sensor.drzwi_toaleta_contact
      - entity: binary_sensor.kuchnia_leak_water_leak
      - entity: binary_sensor.lazienka_leak_water_leak
      - entity: binary_sensor.lazienka_motion_occupancy
      - entity: binary_sensor.sypialnia_motion_occupancy
      - entity: binary_sensor.janek_motion_occupancy
      - entity: binary_sensor.korytarz_motion_occupancy
      - entity: binary_sensor.dafang_online
      - entity: binary_sensor.yeelight_salon_4_online
      - entity: binary_sensor.sharp_online
      - entity: binary_sensor.yeelight_salon_5_online
      - entity: binary_sensor.lampa_korytarz_drzwi_online
      - entity: binary_sensor.xbox_online
      - entity: binary_sensor.chromecast_pokoj_janka_online
      - entity: binary_sensor.chromecast_salon_online
      - entity: binary_sensor.chromecast_sypialnia_online
      - entity: binary_sensor.bedside_online
      - entity: binary_sensor.listwa_salon_online
      - entity: binary_sensor.roleta_kuchnia_online
      - entity: binary_sensor.roleta_sypialnia_online
      - entity: binary_sensor.roleta_pokoj_janka_online
      - entity: binary_sensor.roborock_online
      - entity: binary_sensor.airpurifier_online
      - entity: binary_sensor.smartmi2_online
      - entity: binary_sensor.shelly_4_sypialnia_online
      - entity: binary_sensor.yeelight_biurko_online
      - entity: binary_sensor.shelly1_toaleta_online
      - entity: binary_sensor.shelly_2_kuchnia_online
      - entity: binary_sensor.zen_pc_old_online
      - entity: binary_sensor.rmmini_online
      - entity: binary_sensor.zen_pc_online
      - entity: binary_sensor.lampa_kuchnia_1_online
      - entity: binary_sensor.lampa_kuchnia_2_online
      - entity: binary_sensor.ambient_regal_online
      - entity: binary_sensor.lampa_kuchnia_3_online
      - entity: binary_sensor.ambient_obraz_online
      - entity: binary_sensor.lampa_korytarz_online
      - entity: binary_sensor.salon_regal_switch_online
      - entity: binary_sensor.drukarka_online
      - entity: binary_sensor.lampa_salon_switch_online
      - entity: binary_sensor.yeelight_salon_1_online
      - entity: binary_sensor.shelly_1_pokoj_jan_online
      - entity: binary_sensor.yeelight_salon_2_online
      - entity: binary_sensor.sonoff_rtv_jan_online
      - entity: binary_sensor.updater
      - entity: binary_sensor.lampa_korytarz_drzwi_nightlight
      - entity: binary_sensor.lampa_korytarz_nightlight
      - entity: binary_sensor.bedside_nightlight
      - entity: binary_sensor.192_168_1_22_nightlight
      - entity: person.zenedith
      - entity: person.kate
      - entity: sensor.purifier_humidity
      - entity: sensor.purifier_aqi
      - entity: sensor.purifier_filter_type
      - entity: sensor.purifier_filter_life_remaining
      - entity: sensor.purifier_mode
      - entity: sensor.motor_speed
      - entity: sensor.purifier_temperature
      - entity: sensor.spotify_source
      - entity: sensor.vacuum_battery
      - entity: sensor.vacuum_cleaning_time
      - entity: sensor.vacuum_main_brush
      - entity: sensor.vacuum_side_brush
      - entity: sensor.vacuum_status
      - entity: sensor.vacuum_filter
      - entity: sensor.vacuum_cleaning_count
      - entity: sensor.vacuum_fan
      - entity: sensor.vacuum_cleaned_area
      - entity: sensor.time_online
      - entity: sensor.climate_pokoj_janka_battery
      - entity: sensor.climate_salon_battery
      - entity: sensor.climate_sypialnia_battery
      - entity: sensor.zmietekv2_battery
      - entity: sensor.humidifier_motor_speed
      - entity: sensor.humidifier_temperature
      - entity: sensor.humidifier_humidity
      - entity: sensor.humidifier_depth
      - entity: sensor.humidifier_target_humidity
      - entity: sensor.humidifier_mode
      - entity: sensor.memory_free
      - entity: sensor.rpi_power_status
      - entity: sensor.cpu_temperature
      - entity: sensor.disk_use_percent_home
      - entity: sensor.processor_use
      - entity: sensor.memory_use_percent
      - entity: sensor.swap_use_percent
      - entity: sensor.last_boot
      - entity: sensor.roleta_pokoj_janka_power
      - entity: sensor.zigbee2mqtt_version
      - entity: sensor.roleta_kuchnia_power
      - entity: sensor.coordinator_version
      - entity: sensor.bridge_state
      - entity: sensor.korytarz_motion_battery
      - entity: sensor.janek_motion_battery
      - entity: sensor.sypialnia_motion_battery
      - entity: sensor.lazienka_motion_battery
      - entity: sensor.kuchnia_temp_battery
      - entity: sensor.korytarz_motion_illuminance
      - entity: sensor.kuchnia_temp_pressure
      - entity: sensor.janek_motion_illuminance
      - entity: sensor.kuchnia_temp_humidity
      - entity: sensor.sypialnia_motion_illuminance
      - entity: sensor.kuchnia_temp_temperature
      - entity: sensor.lazienka_motion_illuminance
      - entity: sensor.korytarz_temp_battery
      - entity: sensor.korytarz_temp_pressure
      - entity: sensor.lazienka_leak_battery
      - entity: sensor.korytarz_temp_humidity
      - entity: sensor.kuchnia_leak_battery
      - entity: sensor.korytarz_temp_temperature
      - entity: sensor.okno_kuchnia_contact_battery
      - entity: sensor.drzwi_toaleta_contact_battery
      - entity: sensor.drzwi_lazienka_contact_battery
      - entity: sensor.okno_sypialnia_contact_battery
      - entity: sensor.okno_janek_contact_battery
      - entity: sensor.drzwi_wejsciowe_contact_battery
      - entity: sensor.drzwi_balkonowe_contact_battery
      - entity: sensor.kuchnia_smoke_battery
      - entity: sensor.zmywarka_version
      - entity: sensor.pralka_version
      - entity: sensor.rtv_jan_version
      - entity: sensor.zmietek_version
      - entity: sensor.listwa_sypialnia_version
      - entity: sensor.listwa_rtv_version
      - entity: sensor.swiatlo_sypialnia_version
      - entity: sensor.salon_regal_version
      - entity: sensor.lampa_salon_version
      - entity: sensor.swiatlo_pokoj_janka_version
      - entity: sensor.swiatlo_kuchnia_power
      - entity: sensor.roleta_sypialnia_power
      - entity: sensor.sonoff_firmware_version
      - entity: sensor.asuswrt_download_speed
      - entity: sensor.asuswrt_upload_speed
      - entity: sensor.asuswrt_upload
      - entity: sensor.asuswrt_download
      - entity: sensor.transmission_completed_torrents
      - entity: sensor.zene_iphone_battery_state
      - entity: sensor.speedtest_ping
      - entity: sensor.transmission_active_torrents
      - entity: sensor.zene_iphone_battery_level
      - entity: sensor.transmission_status
      - entity: sensor.iphone_battery_level
      - entity: sensor.transmission_total_torrents
      - entity: sensor.iphone_battery_state
      - entity: sensor.transmission_started_torrents
      - entity: sensor.transmission_up_speed
      - entity: sensor.transmission_paused_torrents
      - entity: sensor.transmission_down_speed
      - entity: sensor.hacs
      - entity: sensor.floors_descended
      - entity: sensor.ssid
      - entity: sensor.battery_level
      - entity: sensor.steps
      - entity: sensor.geocoded_location
      - entity: sensor.last_update_trigger
      - entity: sensor.average_active_pace
      - entity: sensor.battery_state
      - entity: sensor.bssid
      - entity: sensor.activity
      - entity: sensor.distance
      - entity: sensor.floors_ascended
      - entity: sensor.connection_type
      - entity: sensor.sim_1
      - entity: sensor.airly_pm2_5_percent
      - entity: sensor.airly_pm10_percent
      - entity: sensor.airly_pm1
      - entity: sensor.airly_pm10
      - entity: sensor.airly_caqi_level
      - entity: sensor.airly_pm2_5
      - entity: sensor.airly_caqi
      - entity: sensor.mi_t_e72e017168dc
      - entity: sensor.mi_h_e72e017168dc
      - entity: sensor.mi_t_c47c8d6b1ab3
      - entity: sensor.mi_c_c47c8d6b1ab3
      - entity: sensor.mi_m_c47c8d6b1ab3
      - entity: sensor.mi_l_c47c8d6b1ab3
      - entity: sensor.mi_t_c47c8d6b24c7
      - entity: sensor.mi_l_c47c8d6b24c7
      - entity: sensor.mi_m_c47c8d6b24c7
      - entity: sensor.mi_c_c47c8d6b24c7
      - entity: sensor.mi_l_c47c8d6a0192
      - entity: sensor.mi_m_c47c8d6a0192
      - entity: sensor.mi_t_c47c8d6a0192
      - entity: sensor.mi_c_c47c8d6a0192
      - entity: sensor.mi_m_c47c8d69fef0
      - entity: sensor.mi_c_c47c8d69fef0
      - entity: sensor.mi_t_c47c8d69fef0
      - entity: sensor.mi_l_c47c8d69fef0
      - entity: sensor.birthday_kasia
      - entity: sensor.birthday_zene
      - entity: sensor.birthday_martyna
      - entity: sensor.birthday_rodzice
      - entity: sensor.birthday_paulina
      - entity: sensor.birthday_jan
      - entity: sensor.anniversary_our_wedding
      - entity: sun.sun
      - entity: timer.lazienka
      - entity: timer.toaleta
      - entity: timer.sypialnia
      - entity: timer.pokoj_janka
      - entity: timer.korytarz
      - entity: timer.zigbee_permit_join
