title: Zene Home
views:
  - !include default_view.yaml
  - !include main_view.yaml
  - !include other_view.yaml
  - !include weather_view.yaml
  - !include automation_view.yaml

#resources:
#  - url: /local/lovelace/mini-media-player/mini-media-player.js?v=0.8.7
#    type: module
#  - url: /local/lovelace/lovelace-slider-entity-row/slider-entity-row.js?v=1
#    type: js
