switch:
  - platform: broadlink
    friendly_name: broadlink
    timeout: 15
    host: 192.168.1.163
    mac: '78:0f:77:d9:23:fa'
    type: rm_mini
    switches:
      denon_power:
        friendly_name: "Denon power"
        command_on: 'JgBQAAgbCF8IGggbBz0KGQsXCRoIXwg9Bz0GHAgABcgKGAg8CD0IGghfCTwLOgg8CD0IGweBCgAFowkaBz0IGgg9CzoJPAg9Bj4IgQkaCxcHAA0FAAAAAAAAAAA='
        command_off: ''
      denon_volume:
        friendly_name: "Denon volume"
        command_on: 'JgBSAAgaCl0JGgleCRkIGwgaCYAIPQc9BxwJAAXGCBoHPgk8CBoJGgY+CTsHPggaCjsJGgmACQAFpAgaCV4JPAg8CzoJGgY+CD0JPAU/CBoJGgcADQUAAAAAAAA='
        command_off: 'JgBMAAgaC1wIGwg8CV8IGgiBCjoIPQgaCwAFxAwXBz4KOwgaCV4IgAsYCzoJGQk8CD0KAAWiDBcKOgccCD0IGgpdC1wIPAt/ChgIGwYADQUAAAAAAAAAAAAAAAA='

input_boolean:
  broadlink_denon_receiver:
    name: Denon Sound
    icon: mdi:surround-sound

input_select:
  broadlink_denon_input:
    name: Denon Input
    options:
      - "TV"
      - "Tuner"

automation:
  - alias: Denon Receiver On
    trigger:
      - platform: state
        entity_id: input_boolean.broadlink_denon_receiver
        to: 'on'
    action:
      - service: switch.broadlink_send_packet_192_168_1_163
        data:
          packet: 'JgBQAAgbCF8IGggbBz0KGQsXCRoIXwg9Bz0GHAgABcgKGAg8CD0IGghfCTwLOgg8CD0IGweBCgAFowkaBz0IGgg9CzoJPAg9Bj4IgQkaCxcHAA0FAAAAAAAAAAA='

  - alias: Denon Receiver Off
    trigger:
      - platform: state
        entity_id: input_boolean.broadlink_denon_receiver
        to: 'off'
    action:
      - service: switch.broadlink_send_packet_192_168_1_163
        data:
          packet: 'JgBQAAgbCF8IGggbBz0KGQsXCRoIXwg9Bz0GHAgABcgKGAg8CD0IGghfCTwLOgg8CD0IGweBCgAFowkaBz0IGgg9CzoJPAg9Bj4IgQkaCxcHAA0FAAAAAAAAAAA='

  - alias: Select Denon Input TV
    trigger:
      - platform: state
        entity_id: input_select.denon_input
        to: "TV"
    action:
      - service: switch.broadlink_send_packet_192_168_1_163
        data:
          packet: 'JgBSAAcbCToJGwkaCV4KGAYdCDwKOwg8CTwHGwkABcYJGgc9CzoJGgpdCDwGHQg8Cl0IGgs6Bz4LAAWhCRoHYAo7CDwKGQYcCDwHHAcbC34IGwoADQUAAAAAAAA='

  - alias: Select Denon Input Tuner
    trigger:
      - platform: state
        entity_id: input_select.denon_input
        to: "Tuner"
    action:
      - service: switch.broadlink_send_packet_192_168_1_163
        data:
          packet: 'JgCAAAgaCV4IGwhfCF8IGgg9CTsKOwcbCQAFxgoZCDwJPAgaCV8IXwg8CV4IGgo7Bz0KAAWjCRkKOwgaCTwJPAhfCD0IGgiBCBoHHAcABcgJOwoZBxsJPAc+CV4IPQU/CBoIXwg9CQAFowpdCBsGHAccCF8IPAgbBhwIXwg8CjsIAA0FAAAAAAAAAAA='
