switch:
  - platform: broadlink
    friendly_name: broadlink
    timeout: 15
    host: 192.168.1.163
    mac: '78:0F:77:D9:23:FA'
    type: rm_mini
    switches:
      denon_power:
        friendly_name: "Denon power"
        command_on: "JgBOAAoZCl0IGghfCD0IGgdgCDsKPQYcCAAFxwcbBz4IPQgaCBsGPgiBCD0IPQgbBj4GPggABaUIGwk7BhwIPQc9CD0IPQk8CYAIGwcbBgANBQAAAAAAAAAAAAA="
        command_off: "JgCOAAgaCl0IGgk8CV8IGghfCjoGPwcbCgAFxQgbBj4LOgccCjoHHAp/CDwLOgsXBj8HPQsABaIKGAc+CRoJOwsYBz4GHAc+CjoHggkaBhwKAAWjChgKOwgaCRoJGgg8CBoIPQY+Cl0KGApeCTsGAAWmCxgHPgoYBh0GHApdChgKGQYcCjwIOwc+CRoIGggADQUAAAAAAAAAAAAA"
      denon_volume:
        friendly_name: "Denon volume"
        command_on: "JgC6AAkZCF8IGghfChkLFwgbCIEIPQc9BxsIAAXICRkJOwg9BxwHXwo7CzoIGgk8CBsHPQc9CQAFpAoZBz0HGwo7CD0JPAkZCjsIPAt+CxgLFwcABcgIPAoZBxsJPAo7CD0GPggbChgIGghfCD0JAAWjC1wLGAcbBxsJXgccCV4JPAo6CDwKOwoABaMJGQleCBsGHAcbCYEIPAk8CTwHPQsABgkIPAk8CRoIPAccCD0IPAiBCD0JGQgbCAANBQAAAAAAAAAAAAAAAAAA"
        command_off: "JgAgAQgaCF8IGgkaBxsJXgkZCYEIPAY/BhwIAAXHCBsIPAk8CBoJPAcbCYEIGgg9CBoHPgY+CQAFpAkZBz0IGwg9CBoJPAcbCV4JPAmACBoHHAgABccIPAccCBoIXwkaCIEIPQgaCF8IPAcABaYJXggaBxwIGgleCRoIGgc+CIEIPAk8CAAFpQgaCTwGHAgaBxwHPQpeCDwJGgYcCD0JOwoABegGHAg8CjsJGQccBz4JPAg8CTwIPAleCRkKAAWjCV4IGgo7CTwGHAk8CV4IGgk8CIEIAAXHCV4JGQo7CTwGHQgaCIEIPApdCgAFxQwXBj4KOwkaCl0KOgY/BxsKOwgaCzoHPQsABaIIGgtcCTwJGgo7BhwIGgc+Bj4LfggaCwANBQAAAAAAAAAA"

input_boolean:
  broadlink_denon_receiver:
    name: Denon
    icon: mdi:surround-sound

input_select:
  broadlink_denon_input:
    name: Denon Input
    initial: TV
    options:
      - 'TV'
      - 'Tuner'

automation:
  - alias: Denon Receiver On
    trigger:
      - platform: state
        entity_id: input_boolean.broadlink_denon_receiver
        to: 'on'
    action:
      - service: switch.broadlink_send_packet_192_168_1_163
        data:
          packet:
            - "JgBOAAoZCl0IGghfCD0IGgdgCDsKPQYcCAAFxwcbBz4IPQgaCBsGPgiBCD0IPQgbBj4GPggABaUIGwk7BhwIPQc9CD0IPQk8CYAIGwcbBgANBQAAAAAAAAAAAAA="

  - alias: Denon Receiver Off
    trigger:
      - platform: state
        entity_id: input_boolean.broadlink_denon_receiver
        to: 'off'
    action:
      - service: switch.broadlink_send_packet_192_168_1_163
        data:
          packet:
            - "JgCOAAgaCl0IGgk8CV8IGghfCjoGPwcbCgAFxQgbBj4LOgccCjoHHAp/CDwLOgsXBj8HPQsABaIKGAc+CRoJOwsYBz4GHAc+CjoHggkaBhwKAAWjChgKOwgaCRoJGgg8CBoIPQY+Cl0KGApeCTsGAAWmCxgHPgoYBh0GHApdChgKGQYcCjwIOwc+CRoIGggADQUAAAAAAAAAAAAA"

  - alias: Select Denon Input TV
    trigger:
      - platform: state
        entity_id: input_select.broadlink_denon_input
        to: 'TV'
    action:
      - service: switch.broadlink_send_packet_192_168_1_163
        data:
          packet:
            - "JgB8AAkaCV4IGgs6CF8IGgs6CjsGPwgaCQAFxAkcCDwKOwgaC34LXAk8Cl0IGgc+CDwLAAWiCRkHPggaCTwJGgleCTwIGgmACBoHHAgABccJPAYcCBsIXwg8Cl0MfQgbC1wIPAYABacKXQgaBxwHGwo7CD0IPQhfCDwJPAgADQUAAAAAAAAAAAAAAAA="

  - alias: Select Denon Input Tuner
    trigger:
      - platform: state
        entity_id: input_select.broadlink_denon_input
        to: 'Tuner'
    action:
      - service: switch.broadlink_send_packet_192_168_1_163
        data:
          packet:
            - "JgCAAAgaCV4JGghfCF8IGgg9CDwKOwgaCQAFxgoZCDwKOwkaCV4JXgg8CToJGwgbBj4HPggABaQJGgg9CBoIPQg7CV8IPQgaCYEIGggbBgAFyQg8CBsGHAg9CDwJXgk8Bj8IGghfCDwIAAWlCl0KGAgbBhwJXgk8CD0IXwg8CjsIAA0FAAAAAAAAAAA="
