switch:
  - platform: broadlink
    friendly_name: broadlink
    timeout: 15
    host: 192.168.1.163
    mac: '78:0f:77:d9:23:fa'
    type: rm_mini
    switches:
      denon_power:
        friendly_name: "Denon power"
        command_on: 'JgC4AAABJJYQFBE5EBQQFRA5EDkRFBAVEDkQFBE5EDkQFRAUEDkRORAUETkQFBAVEBQRFBAVEBQQOhAUEDkRORA5EDkQORE5EAAFIwABJUsRAAxKAAElSxAADEwAASRMEAAMSwABJUsQAAxMAAEkTBAADEsAASVLEQAMSwABJEwQAAxLAAElSxEADEsAASRMEAAMSwABJUwQAAxLAAElSxAADEsAASVMEAAMSwABJUsRAAxLAAEkTBAADQU='
        command_off: 'JgDwAAABJZUQFRA5EBUQFBA5ETkQFBEUEDkQFRA5EDkQFRAUETkQORAUETkQORA5EBUUNRAVEBQRORAUEBUQFBE5EBQRORA5EAAFIQABJksRAAxKAAElSxAADEsAASVLEQAMSgABJUwQAAxLAAEkTBAADEsAASVLEQAMSgABJUwQAAxLAAEkTBAADEsAASVLEQAMSgABJUwQAAxLAAEkTBAADEsAASVLEQAMSgABJUwQAAxLAAEkTBAADEsAASVLEQAMSgABJUwQAAxLAAEkTBAADEsAASVLEQAMSgABJUwQAAxLAAEkTBAADEsAASVLEAANBQAAAAAAAAAA'
      denon_volume:
        friendly_name: "Denon volume"
        command_on: "JgCEAxMSEjcTEhMSExETEhMSExEUNhMSEzYTNxM2FDYTNxM2EwAE9gABJpMTEhM2ExITEhM2ExITNxM2EzcTEhM2EzcTERM3EzcSEhMSEzcTERMSExITEhISExITNxMREzcTNhM3EzcTNhQ2EwAE9QABJpQTERM3ExITERM3ExITNhM3EzYTEhM3EzYTEhM2EzcTEhMSEjcTEhMSExETEhMSExITNhMSEzYTNxM3EzYTNxM2EwAE9gABJpMUERM2ExITEhM2ExITNxM2EzcTEhM2EzcTERM3EzcTERMSEzcTERQRExITEhMRExITNxMREzcTNxI3EzcTNhM3EwAE9QABJpQTERM3ExITEhM2ExITNhM3FDUTEhM3EzYUERQ2EjcUERQREzYUERMSExETEhMSExITNhMSEzYTNxQ2EzYUNhM2EwAE9gABJpMUERQ1ExITEhM2FBETNxQ1FDYUERM2EzcUEBM3EzcTERMSFDYTERMSFBETEhMRExITNxMREzcTNxI3EzcTNhQ2FAAE9AABJpQTERM3FBETERM3ExIUNRQ2FDUUERQ2EzYTEhM3EzYUERMSEzYUERQRExETEhQRExITNhQRFDUUNhQ2EzYUNhM2FAAE9QABJ5IUERM2ExIUERQ1FBETNxQ1FDYUERM2FDYTERQ2FDYTERQRFDYTERQRExITEhMRExIUNhMREzcTNxM2FDYTNhM3EwAE9QABJpQSEhM3ExISEhM3ExITNhM3EzYTEhM3EjcTEhM2EzcTEhMSEjcTEhMSEhITEhMSExISNxMSEzYTNxM3EjcTNxM2EwAE9gABJpMTEhM2ExITEhM2ExITNxM2EzcTEhI3EzcTERM3EzcSEhMSEzcSEhMSExITEhISExITNxISEzcTNhM3EzcSNxM3EwAE9QABJpQSEhM3ExISEhM3ExITNhM3EzYTEhM3EzYTEhM2EzcTEhMSEjcTEhMSEhITEhMSExITNhMSEzYTNxM2EzcTNxM2EwAE9AABKJMTEhM2ExITEhM2ExITNxM2EzcTEhI3EzcTERM3EzYTEhMSEzcSEhMSExITEhISExIUNhMREzcTNhQ2EzcSNxM3EwAE9QABJ5ITEhM3FBESEhM3ExITNhM3EzYTEhM3EzYUERQ1FDYUERQQFDYUERQREhITEhMSExETNxMSEzYTNxM2EzcTNxI3EwANBQAAAAA="
        command_off: "JgCEAxI4EjcSExITEhISExITEhMSEhITEjgSNxI4EzYTNxM2EwAE9gABJpMTEhM3ExEUERM3ExEUNhM3EzYTEhM2FDYTEhM2EzcTEhM2EzcTERQRExITEhMRFBEUERMSEzYTNxM2FDYTNhQ2EwAE9QABJ5MTEhM2ExITEhM2ExITNxM2EzcTERQ2EzcTERM3EzYUERM3EzYTEhMSExITERMSExITEhMREzcTNhQ2EzcTNhM3EwAE9QABJpMUERM3ExITERM3ExITNhM3EzYTEhM3EzYTEhM2FDYTEhM2EzcTEhMRExITEhMSExETEhMSEzYTNxM3EzYTNxM2EwAE9gABJpMTEhM2ExITEhM2FBETNxM2EzcTEhM2EzcTEhM2EzcTERM3EzYUERMSExITERQRExITEhMREzcTNhQ2EzcTNhM3EwAE9QABJpQTERQ2ExITEhM2ExITNhM3EzYUERM3EzYTEhM3EzYTEhM2FDYTEhMSExETEhMSExITERMSEzcTNhM3EzYTNxM2FAAE9QABJpMTEhM3ExETEhM3ExETNxM2FDYTEhM2EzcTEhM2EzcTEhM2EzcTERMSExITEhMRExITEhMSEzYTNxM2EzcTNhQ2EwAE9QABJ5MTEhM2ExITEhM2ExITNxM2EzcTERM3EzYUERM3EzYTEhM3EzYTEhMSExEUERMSExITERQREzcTNhM3EzYUNhM3EwAE9QABJpMUERM3ExITERM3ExITNhM3EzYTEhM2FDYTEhM2FDYTEhM2EzcTEhMRExITEhMSExETEhMSEzYTNxM2FDYTNhQ2EwAE9gABJpMTEhM2ExITEhM2ExITNxM2EzcTEhM2EzcTERM3EzYUERM3EzYTEhMSExITERMSExITEhMREzcTNhQ2EzcTNhM3EwAE9QABJpMUERM3ExITERM3ExITNhM3EzYTEhM3EzYTEhM2FDYTEhM2EzcTEhMRFBETEhMSExETEhMSEzYUNhM3EzYTNxM2EwAE9gABJpMTEhM2FBETEhM2FBETNxM2EzcTEhM2EzcTEhM2EzcTERM3EzYUERMSExITERQRExITEhMRFDYTNxM2EzcTNhM3EwAE9QABJZUSExI3EhMSEhM3EhMSNxI4EjcTEhE5EjcSExE5ETgRFBE4ETkRFBEUERMRFBEUERQQFBEUETkROBE5ETgRORE4EQANBQAAAAA="

input_boolean:
  receiver:
    name: Denon Sound
    icon: mdi:surround-sound

input_select:
  denon_input:
    name: Denon Input
    options:
      - "TV"
      - "Tuner"

automation:
  - alias: Denon Receiver Toggle
    trigger:
      - platform: state
        entity_id: input_boolean.receiver
    action:
      - service: switch.broadlink_send_packet_192_168_1_66
        data:
          packet: "JgCoAQABJZQRFBE4ERQRFBE4ERQRORE4ExIRFBE4ETkRFBE4ETkRFBA5ETkRExE5ERQRExE5ETkRExEUETkRExE5ETgRFBEUEQAFHAABJE0RAAxJAAEmSxIADEgAASZLEgAMSAABJksSAAxIAAEnShMADEcAASdKEwAMRwABJ0oTAAxHAAEnShMADEcAASdKEwAMRwABJ0oTAAxHAAEnShMADEcAASdKEwAMRwABJ0oTAAxHAAEnShMADEcAASdKEwAMRwABJ0oTAAxHAAElTBEADEkAASVMEQAMSgABJkoTAAxHAAElTBEADEkAASdIFQAMSAABJEwRAAxKAAEmShMADEgAASZKEwAMSAABJkoTAAxIAAEmShMADEgAASZKEwAMSAABJkoTAAxIAAEmShMADEgAASZKEwAMSAABJkoTAAxIAAEmShMADEgAASVLEgAMSQABJkoTAAxIAAEmShMADEgAASZKEwAMSAABJkoUAAxHAAEmShQADEcAASZKFAAMRwABJkoUAAxHAAEmShQADEcAASZKFAAMRwABJkoUAAxHAAEmShQADQU="

  - alias: Select Denon Input TV
    trigger:
      - platform: state
        entity_id: input_select.denon_input
        to: "DVD"
    action:
      - service: switch.broadlink_send_packet_192_168_1_66
        data:
          packet: "JgDYAgABJJYRExI4ERQRExI4ERQROBE5ETgSExE5ETgRFBE5ETgRFBE5ERMRORE4ERQRFBEUERMRFBE5ERMSExE5ETgRORE4EgAE9wABJE0RAAxJAAEkTREADEkAASRNEQAMSgABJEwRAAxKAAEkTBEADEoAASRMEQAMSgABJEwRAAxKAAEkTBIADEkAASRNEQAMSQABJE0RAAxJAAEkTREADEkAASRNEQAMSQABJUwRAAxJAAElTBEADEoAASRMEQAMSgABJEwRAAxKAAEkTBEADEoAASRNEQAMSQABJE0RAAxJAAEkTREADEkAASVMFAAMRwABJEwRAAxKAAEkTBEADEoAASRMEQAMSgABJE0RAAxJAAEkTREADEkAASRNEQAMSQABJUwRAAxKAAEkTBEADEoAASRMEQAMSgABJEwRAAxKAAEkTBEADEoAASRMEQAMSgABJEwRAAxKAAEkTBEADEoAASRMEQAMSgABJEwRAAxKAAEkTBEADEoAASRNEQAMSQABJE0RAAxJAAElTBEADEoAASRMEQAMSgABJEwRAAxKAAEkTBEADEoAASRMEgAMSQABJE0RAAxJAAEkTREADEkAASVMEQAMSgABJEwRAAxKAAEkTBEADEoAASRMEgAMSQABJE0RAAxJAAEkTREADEoAASRMEQAMSgABJEwRAAxKAAEkTBEADEoAASRMEgAMSQABJE0RAAxJAAElTBEADEoAASRMEQAMSgABJEwRAAxKAAEkTBEADEoAASRNEQAMSQABJE0RAAxJAAElTBEADEkAASVMEQAMSgABJEwRAAxKAAEkTBEADEoAASRNEQAMSQABJE0RAAxJAAElTBEADEoAASRMEQAMSgABJEwRAAxKAAEkTBIADEkAASRNEQAMSQABJUwRAAxKAAEkTBEADEoAASRMEQAMSgABJEwRAAxKAAEkTREADEkAASRNEQAMSQABJUwRAA0F"
